// Generated by scripts/deploy/generate-pilot-release.mjs. Do not edit manually.
export const GENERATED_PILOT_RELEASE = Object.freeze({
  "packageVersion": "0.1.0",
  "appVersion": "rehabmind-pilot-app-0.1.0+local-c96820b7f397-dirty-df408ed80802.c96820b7f397",
  "knowledgeVersion": "rehabmind-pilot-knowledge-0.1.0",
  "decisionVersion": "rehabmind-pilot-decision-0.1.0",
  "ruleVersion": "rehabmind-pilot-decision-0.1.0",
  "buildId": "local-c96820b7f397-dirty-df408ed80802",
  "commitSha": "c96820b7f397e6b970dfdd18ce53da4a3549b6f4"
} as const);
