// Generated by scripts/deploy/generate-pilot-release.mjs. Do not edit manually.
export const GENERATED_PILOT_RELEASE = Object.freeze({
  "packageVersion": "0.1.0",
  "appVersion": "rehabmind-pilot-app-0.1.0+local-fdaee6fc5ca3-dirty-702a36f81e82.fdaee6fc5ca3",
  "knowledgeVersion": "rehabmind-pilot-knowledge-0.1.0",
  "decisionVersion": "rehabmind-pilot-decision-0.1.0",
  "ruleVersion": "rehabmind-pilot-decision-0.1.0",
  "buildId": "local-fdaee6fc5ca3-dirty-702a36f81e82",
  "commitSha": "fdaee6fc5ca3beb246ed5184650540d6a78507a8"
} as const);
