// Generated by scripts/deploy/generate-pilot-release.mjs. Do not edit manually.
export const GENERATED_PILOT_RELEASE = Object.freeze({
  "packageVersion": "0.1.0",
  "appVersion": "rehabmind-pilot-app-0.1.0+local-5af6280c6f60-dirty-cadc04264383.5af6280c6f60",
  "knowledgeVersion": "rehabmind-pilot-knowledge-0.1.0",
  "decisionVersion": "rehabmind-pilot-decision-0.1.0",
  "ruleVersion": "rehabmind-pilot-decision-0.1.0",
  "buildId": "local-5af6280c6f60-dirty-cadc04264383",
  "commitSha": "5af6280c6f60f3236363dac6150a6e4ddef550d6"
} as const);
