export const ACUTE_SCENARIOS = {
  ankle: {
    label: "急性踝关节扭伤",
    code: "ANKLE / 04",
    route: "acute-sprain" as const,
    routeLabel: "急性扭伤处理路线",
    routeDescription: "先判断损伤严重程度，再从保护、承重、活动、力量和平衡逐步恢复。",
    sample: "昨天打球落地时右脚崴了一下，脚踝外侧肿了，现在走路有点跛。",
    profile: {
      region: "右踝",
      location: "外侧",
      behavior: "落地内翻后肿胀、走路受限",
      onset: "伤后约 24 小时",
    },
    risks: [
      {
        title: "明显错位、异常角度或足部循环异常",
        detail: "这里指疑似脱位或骨折造成的轮廓、角度异常，以及足部颜色、温度或感觉变化；不包含单纯软组织肿胀。",
        level: "urgent" as const,
      },
      { title: "完全无法承重或走四步", detail: "受伤后和现在都无法完成基本承重与短距离行走。", level: "assessment" as const },
      { title: "骨性位置明显压痛", detail: "踝部或足部骨性突起处有非常明确、集中的压痛。", level: "assessment" as const },
      { title: "快速大量肿胀或持续恶化", detail: "短时间内明显肿胀，疼痛和功能持续快速下降。", level: "assessment" as const },
    ],
    question: "受伤当时能否继续走动？现在是否可以完成短距离承重？",
    hypotheses: [
      {
        id: "ankle-sprain-path",
        title: "急性外侧踝扭伤恢复路径",
        dimension: "local" as const,
        base: 72,
        summary: "受伤机制和外侧肿胀符合常见急性踝扭伤表现，处理重点是阶段化恢复功能。",
        chain: ["落地内翻机制", "外侧软组织受力", "疼痛与肿胀", "承重和稳定能力下降"],
        clues: ["明确急性内翻机制", "外侧肿胀", "走路出现跛行"],
        unknown: "需要确认骨性压痛、承重能力和肿胀变化。",
        weights: { functionLoss: 10, swelling: 7, bruising: 5 },
      },
      {
        id: "ankle-load",
        title: "当前承重与保护剂量需要调整",
        dimension: "context" as const,
        base: 58,
        summary: "完全不动与过早高负荷都可能影响恢复，需要寻找安全承重窗口。",
        chain: ["急性反应期", "承重能力下降", "保护或负荷失衡", "步态与功能受限"],
        clues: ["目前走路有跛行", "处于伤后早期"],
        unknown: "需要记录短距离承重后当时和数小时后的反应。",
        weights: { functionLoss: 14, highPain: 6, lingering: 8 },
      },
      {
        id: "ankle-motion",
        title: "肿胀与疼痛限制踝部活动",
        dimension: "mobility" as const,
        base: 51,
        summary: "急性肿胀可能暂时限制踝泵、背屈和正常步态。",
        chain: ["肿胀与疼痛", "活动范围减少", "小腿泵与步态改变", "功能恢复变慢"],
        clues: ["外侧肿胀", "步态改变"],
        unknown: "需要观察舒适范围的屈伸活动和肿胀趋势。",
        weights: { swelling: 12, functionLoss: 5 },
      },
      {
        id: "ankle-control",
        title: "平衡与踝周控制需要后续重建",
        dimension: "control" as const,
        base: 34,
        summary: "急性期之后，单腿平衡、反应能力和落地控制决定能否安全回归。",
        chain: ["受伤后感觉与控制下降", "单腿稳定变差", "落地策略受限", "再次扭伤风险增加"],
        clues: ["急性踝扭伤常影响稳定和信心"],
        unknown: "早期不急于测试，需要在正常承重后逐步评估。",
        weights: { persistent: 8, concern: 8 },
      },
      {
        id: "ankle-environment",
        title: "鞋、场地与回场节奏影响复发",
        dimension: "chain" as const,
        base: 26,
        summary: "落地环境、鞋具和过早回场可能增加后续风险。",
        chain: ["外部环境或疲劳", "落地策略受影响", "踝部负荷增加", "恢复或回场受阻"],
        clues: ["球类落地场景"],
        unknown: "需要了解场地、鞋具、疲劳和既往崴脚史。",
      },
      {
        id: "ankle-other",
        title: "既往反复崴脚或慢性不稳",
        dimension: "other" as const,
        base: 22,
        summary: "既往扭伤和未完成的功能恢复会改变本次康复重点。",
        chain: ["既往扭伤", "稳定与反应能力未恢复", "再次内翻", "复发循环"],
        clues: ["当前尚未提供既往史"],
        unknown: "需要确认过去是否反复崴脚以及是否完成过平衡和回场训练。",
        weights: { persistent: 6, concern: 6 },
      },
      {
        id: "ankle-ruleout",
        title: "骨折或较严重损伤需要排除",
        dimension: "ruleout" as const,
        base: 12,
        summary: "无法承重、骨性压痛、明显变形或神经血管异常应优先专业评估。",
        chain: ["高风险表现", "超出教练筛查边界", "停止功能测试", "转介影像或专业评估"],
        clues: ["目前有肿胀和跛行，需要主动确认"],
        unknown: "必须完成承重、骨性压痛、变形与足部感觉检查。",
        weights: { functionLoss: 38, swelling: 12, bruising: 8, highPain: 8 },
      },
    ],
    tests: [
      {
        title: "支持下的舒适承重",
        instruction: "在有支撑、风险问题均为阴性的前提下，观察轻度重心转移是否可控。",
        target: "ankle-load",
        options: [
          { label: "可以控制", delta: 8, meaning: "可以从低剂量承重开始逐步恢复" },
          { label: "明显受限", delta: 14, meaning: "当前保护和承重剂量是优先问题" },
          { label: "暂不测试", delta: 0, meaning: "保持保护，等待进一步评估或复核" },
        ],
      },
      {
        title: "舒适范围踝泵",
        instruction: "不进入明显疼痛终点，缓慢做足踝上下活动，观察幅度和反应。",
        target: "ankle-motion",
        options: [
          { label: "可控且逐渐放松", delta: 9, meaning: "适合保留低剂量活动并观察肿胀" },
          { label: "幅度明显受限", delta: 13, meaning: "活动恢复应列为早期重点" },
          { label: "暂不测试", delta: 0, meaning: "当前先以保护和观察为主" },
        ],
      },
      {
        title: "短距离步态观察",
        instruction: "仅在能够承重时，观察步幅、推蹬和保护性跛行，不追求正常速度。",
        target: "ankle-sprain-path",
        options: [
          { label: "轻度受限但可控", delta: 8, meaning: "可进入渐进承重与活动阶段" },
          { label: "明显跛行或不稳", delta: 12, meaning: "功能仍处早期，需要降低任务难度" },
          { label: "暂不测试", delta: 0, meaning: "不强行进行步态验证" },
        ],
      },
    ],
    modules: [
      {
        id: "ankle-base",
        target: "baseline",
        label: "今天先做",
        title: "保护受伤区域并保留安全活动",
        goal: "避免再次扭转，同时防止不必要的长期完全休息。",
        action: "暂停跑跳和变向；根据承重能力使用支撑，记录肿胀、走路和疼痛变化。",
        standardDose: "每 3–4 小时记录一次肿胀与承重变化",
        gentleDose: "以保护和舒适体位为主，暂不强行承重",
        retest: "短距离承重与肿胀趋势",
      },
      {
        id: "ankle-load-module",
        target: "ankle-load",
        label: "早期承重",
        title: "逐步恢复可控承重",
        goal: "在不过度加重反应的前提下恢复正常步态。",
        action: "从双脚重心转移、扶持站立到短距离行走逐级推进，不用跛行距离换训练量。",
        standardDose: "每日多次短时练习，每次后观察 2–4 小时",
        gentleDose: "先进行支持下的轻度重心转移",
        retest: "相同步数后的跛行和肿胀",
      },
      {
        id: "ankle-motion-module",
        target: "ankle-motion",
        label: "早期活动",
        title: "恢复舒适范围踝部活动",
        goal: "逐项找回背屈、跖屈、内翻和外翻的舒适活动。",
        action: "四个方向分别与健侧比较，只练真正受限的方向；背屈受限再检查腓肠肌与比目鱼肌，外侧症状再比较腓骨肌群。",
        standardDose: "每日 3–5 次，每次 1–2 组 × 10 次",
        gentleDose: "每日 3 次，小幅度 6–8 次",
        retest: "活动范围与随后承重反应",
      },
      {
        id: "ankle-control-module",
        target: "ankle-control",
        label: "后续阶段",
        title: "重建小腿、臀腿与平衡能力",
        goal: "让髋、膝、踝共同完成走路、楼梯和单脚控制。",
        action: "先做四向等长发力和坐姿提踵，再进阶弹力带四向力量、双脚提踵、坐站、低台阶上步和扶持单腿平衡。",
        standardDose: "每阶段达到稳定标准后再增加速度或复杂度",
        gentleDose: "先从双脚提踵和扶持平衡开始",
        retest: "单腿提踵、平衡、跳跃与变向标准",
      },
      {
        id: "ankle-context-module",
        target: "context",
        label: "目标动作",
        title: "从上下楼恢复到目标活动",
        goal: "把活动度、力量和平衡带回日常或专项任务。",
        action: "先用低台阶练习上步和控制下步；日常目标达到后，再依次恢复快走、慢跑、落地和计划性变向。",
        standardDose: "每次只增加一个速度或方向变量",
        gentleDose: "先完成无痛快走和基础提踵",
        retest: "训练后与次日的肿胀、稳定和信心",
      },
    ],
    retest: ["同样 10 步的跛行、步幅与推蹬", "原受限活动方向与肿胀趋势", "提踵、平衡和落地控制"],
  },
  hamstring: {
    label: "急性大腿后侧拉伤",
    code: "STRAIN / 05",
    route: "acute-strain" as const,
    routeLabel: "急性肌肉拉伤路线",
    routeDescription: "先判断严重程度，再从保护、低负荷收缩、活动、力量和跑动逐级恢复。",
    sample: "今天冲刺时右侧大腿后面突然拉了一下，当时马上减速停下，现在走路有点紧和痛。",
    profile: {
      region: "右侧大腿后侧",
      location: "腘绳肌区域",
      behavior: "冲刺时突然出现，走路紧痛",
      onset: "伤后数小时",
    },
    risks: [
      { title: "明显凹陷、变形或大范围淤青", detail: "肌肉外观异常，或短时间出现大片淤青和肿胀。", level: "assessment" as const },
      { title: "完全无法正常走路", detail: "无法承重，或每一步都出现明显疼痛和功能丧失。", level: "assessment" as const },
      { title: "坐骨附近剧烈疼痛", detail: "疼痛非常靠近臀下，并伴明显无力或受伤时听到响声。", level: "assessment" as const },
      { title: "麻木、放射或持续恶化", detail: "出现腿部感觉异常，或静息状态下仍快速加重。", level: "urgent" as const },
    ],
    question: "受伤时是高速冲刺、突然劈叉，还是慢速力量动作？当时是否听到响声？",
    hypotheses: [
      {
        id: "strain-path",
        title: "急性腘绳肌拉伤恢复路径",
        dimension: "local" as const,
        base: 72,
        summary: "高速动作中突然出现大腿后侧疼痛，处理重点是保护后逐级恢复收缩和长度负荷。",
        chain: ["高速或长肌长受力", "局部纤维负荷超过耐受", "疼痛与保护性紧张", "走路和跑动受限"],
        clues: ["冲刺时突然出现", "立即减速停止", "大腿后侧局部症状"],
        unknown: "需要确认准确位置、淤青、走路能力和收缩表现。",
        weights: { functionLoss: 10, bruising: 8, pop: 6 },
      },
      {
        id: "strain-protection",
        title: "早期保护与活动剂量需要平衡",
        dimension: "context" as const,
        base: 58,
        summary: "过早强拉或完全不动都不理想，需要保留安全活动并控制刺激。",
        chain: ["急性保护期", "动作与收缩受限", "保护或负荷失衡", "恢复节奏受影响"],
        clues: ["伤后数小时", "走路紧痛"],
        unknown: "需要记录走路、坐姿和低强度收缩后的反应。",
        weights: { functionLoss: 14, highPain: 7, lingering: 9 },
      },
      {
        id: "strain-contraction",
        title: "低强度收缩能力需要逐步恢复",
        dimension: "control" as const,
        base: 47,
        summary: "早期可控等长收缩是连接保护期与力量恢复的重要桥梁。",
        chain: ["疼痛抑制收缩", "力量输出下降", "走路和髋伸受限", "跑动能力下降"],
        clues: ["走路时紧痛", "急性后侧大腿表现"],
        unknown: "需要确认轻度屈膝或髋伸收缩是否可控。",
        weights: { functionLoss: 9 },
      },
      {
        id: "strain-length",
        title: "肌肉长度负荷需要后续分级",
        dimension: "mobility" as const,
        base: 34,
        summary: "恢复不是尽早强拉，而是在适当阶段逐步增加长肌长力量和速度。",
        chain: ["早期拉长敏感", "活动范围暂时下降", "长度负荷能力不足", "高速动作尚未准备好"],
        clues: ["冲刺属于长肌长高速负荷"],
        unknown: "早期不追求拉伸终点，后续根据走路和收缩能力评估。",
        weights: { persistent: 8 },
      },
      {
        id: "strain-running",
        title: "跑动速度与专项能力需要重建",
        dimension: "chain" as const,
        base: 30,
        summary: "力量恢复不等于已经具备高速跑动和疲劳下的专项能力。",
        chain: ["基础力量恢复", "长肌长力量恢复", "跑速逐级增加", "回归冲刺与专项"],
        clues: ["受伤发生在冲刺"],
        unknown: "需要了解项目、最高速度暴露和回场标准。",
        weights: { concern: 7, persistent: 6 },
      },
      {
        id: "strain-other",
        title: "腰椎、神经或既往拉伤影响",
        dimension: "other" as const,
        base: 18,
        summary: "反复拉伤、腰部症状或放射表现会改变评估和恢复重点。",
        chain: ["既往或邻近因素", "动作与神经肌肉表现改变", "局部负荷增加", "恢复或复发受影响"],
        clues: ["当前尚未提供既往史"],
        unknown: "需要询问既往拉伤、腰部症状、麻木和放射表现。",
        weights: { persistent: 6 },
      },
      {
        id: "strain-ruleout",
        title: "较大撕裂或近端损伤需要排除",
        dimension: "ruleout" as const,
        base: 12,
        summary: "明显凹陷、大范围淤青、坐骨附近剧痛或严重功能丧失需要专业评估。",
        chain: ["高风险表现出现", "损伤程度可能较高", "停止自行拉伸和测试", "转介专业评估"],
        clues: ["当前走路受限，需要主动确认"],
        unknown: "必须确认淤青、凹陷、响声、疼痛位置和走路能力。",
        weights: { functionLoss: 35, bruising: 28, pop: 18, highPain: 8 },
      },
    ],
    tests: [
      {
        title: "舒适步态观察",
        instruction: "只观察短距离自然走路，不要求拉大步幅，记录跛行和保护性动作。",
        target: "strain-protection",
        options: [
          { label: "轻度受限但可控", delta: 7, meaning: "可保留低剂量日常活动" },
          { label: "明显跛行", delta: 14, meaning: "当前仍需更高保护和更低负荷" },
          { label: "暂不测试", delta: 0, meaning: "不强行进行步态测试" },
        ],
      },
      {
        title: "低强度屈膝等长",
        instruction: "在舒适角度进行很轻的屈膝对抗，不追求最大力量，观察是否可控。",
        target: "strain-contraction",
        options: [
          { label: "可控", delta: 9, meaning: "可以从低强度等长开始建立收缩能力" },
          { label: "明显受限", delta: 13, meaning: "收缩能力是当前重点，起始剂量需更低" },
          { label: "暂不测试", delta: 0, meaning: "当前先保护并等待复核" },
        ],
      },
      {
        title: "小幅度髋铰链",
        instruction: "保持步幅自然，在很小范围内做髋铰链，观察拉长感是否可控。",
        target: "strain-path",
        options: [
          { label: "可控", delta: 7, meaning: "可逐步恢复舒适范围活动" },
          { label: "明显拉扯痛", delta: 10, meaning: "当前仍处较高敏感阶段，需要降低长度负荷" },
          { label: "暂不测试", delta: 0, meaning: "早期无需强行验证长度负荷" },
        ],
      },
    ],
    modules: [
      {
        id: "strain-base",
        target: "baseline",
        label: "今天先做",
        title: "保护受伤区域并保留舒适活动",
        goal: "避免再次高速拉长，同时减少不必要的完全制动。",
        action: "暂停冲刺、跳跃和强拉伸；保留可控短距离走路，记录疼痛、步态和淤青变化。",
        standardDose: "当天多次短距离活动，避免一次走到明显跛行",
        gentleDose: "以保护为主，只保留必要日常活动",
        retest: "走路自然度与次日反应",
      },
      {
        id: "strain-protection-module",
        target: "strain-protection",
        label: "早期剂量",
        title: "找到不加重的活动窗口",
        goal: "在保护和安全活动之间取得平衡。",
        action: "调整步幅、速度和日常活动总量，让反应保持稳定，不用硬撑换活动量。",
        standardDose: "每次活动后观察数小时与次日反应",
        gentleDose: "缩短步幅与活动时间，必要时增加休息",
        retest: "相同距离后的步态和紧痛",
      },
      {
        id: "strain-contraction-module",
        target: "strain-contraction",
        label: "早期收缩",
        title: "恢复低强度等长收缩",
        goal: "重新建立可控力量输出，为后续动态负荷做准备。",
        action: "在舒适角度进行轻度屈膝或髋伸等长，不追求最大力量和明显疼痛。",
        standardDose: "4–5 × 20–30 秒，低到中等强度",
        gentleDose: "5 × 10–15 秒，轻强度",
        retest: "练习后的走路和次日反应",
      },
      {
        id: "strain-length-module",
        target: "strain-length",
        label: "后续力量",
        title: "逐步增加长肌长与离心能力",
        goal: "让肌肉重新适应髋屈、膝伸和高速动作需求。",
        action: "从桥式、髋铰链到较长肌长的屈膝与罗马尼亚硬拉逐级推进。",
        standardDose: "每阶段 2–3 次稳定训练后再增加长度或负荷",
        gentleDose: "先从短肌长桥式和小幅度髋铰链开始",
        retest: "力量、长度负荷和次日反应",
      },
      {
        id: "strain-running-module",
        target: "strain-running",
        label: "回归跑动",
        title: "从慢跑逐级回到冲刺",
        goal: "恢复速度、加速和疲劳下的专项能力。",
        action: "依次恢复快走、慢跑、次最大速度跑和接近比赛速度，不跨阶段回场。",
        standardDose: "每一速度层级稳定完成 2 次后再提高",
        gentleDose: "先达到无跛行快走和基础力量标准",
        retest: "跑速、动作信心和训练后 24 小时反应",
      },
      {
        id: "strain-context-module",
        target: "context",
        label: "回归信心",
        title: "逐步消除对高速动作的回避",
        goal: "让运动员在客观能力恢复的同时重建信心。",
        action: "用可预测的距离和速度完成成功重复，再逐步加入反应和对抗情境。",
        standardDose: "每次只增加速度、距离或复杂度中的一个变量",
        gentleDose: "先从有节奏的快走和低速技术练习开始",
        retest: "速度暴露后的信心和次日反应",
      },
    ],
    retest: ["自然走路与步幅", "低强度收缩能力", "后期长肌长力量与跑速暴露"],
  },
};
