import type { TrainingEntry } from "./types.ts";

export const TRAINING_ENTRIES: TrainingEntry[] = [
  {
    id: "knee-calf-raise", region: "knee", stage: 2,
    actions: ["heel-raise-standing"],
    title: "扶墙双脚提踵",
    how: "双手轻扶墙，脚跟垂直抬起，停1秒后缓慢落下。",
    purpose: "小腿力量回来了，走路蹬地才有劲，站立时膝盖也更稳。",
    observe: "两侧高度接近，膝盖保持稳定，脚踝不向内外倒。",
    easier: "坐姿提踵或减少高度。",
    harder: "单脚提踵或增加轻负重。",
    dose: { sets: "3组", reps: "每组10～15个" },
    tags: ["calf", "heel-raise", "gait"],
    startPosition: "站立",
  },
  {
    id: "calf-back-standing-raise", region: "calf-local", stage: 2,
    actions: ["heel-raise-standing"],
    title: "双脚站姿提踵",
    how: "扶墙站立，两侧脚跟同时抬起，再缓慢落下。",
    purpose: "站直提踵练腓肠肌，蹬地推进的力量从这里开始回到走路里。",
    observe: "两侧高度接近，不向内外歪。",
    easier: "回到坐姿提踵。",
    harder: "进阶单脚提踵。",
    dose: { sets: "3组", reps: "每组10～15个" },
    tags: ["calf-back", "gastrocnemius", "heel-raise"],
    startPosition: "站立",
  },
  {
    id: "calf-medial-arch", region: "calf-local", stage: 2,
    actions: ["heel-raise-standing"],
    title: "足弓保持与提踵",
    how: "站稳，脚趾放松贴地，轻轻踮脚尖再放下。",
    purpose: "小腿内侧和足弓一起练回来，走路时力量才不从小腿内侧漏掉。",
    observe: "脚趾不抠地，脚跟不向外甩，小腿不跟着转。",
    easier: "扶着墙做，只抬一点点。",
    harder: "增加提踵高度。",
    dose: { sets: "3组", reps: "每组10～15个" },
    tags: ["calf-medial", "arch", "heel-raise"],
    startPosition: "站立",
  },
  {
    id: "calf-back-seated-raise", region: "calf-local", stage: 1,
    actions: ["heel-raise-seated"],
    title: "坐姿提踵",
    how: "坐稳，前脚掌踩地，缓慢抬起脚跟再放下。",
    purpose: "膝盖弯着时比目鱼肌才肯出力——这是伤后最早能做的安全负荷。",
    observe: "小腿后侧发力，节奏稳定。",
    easier: "减小高度或个数。",
    harder: "膝上增加轻负重。",
    dose: { sets: "3组", reps: "每组8～12个" },
    tags: ["calf-back", "soleus", "heel-raise"],
    startPosition: "坐位",
  },
  {
    id: "ankle-achilles-isometric", region: "ankle-foot", stage: 1,
    actions: ["heel-raise-hold"],
    title: "坐姿提踵保持",
    how: "坐稳，前脚掌踩地，缓慢抬起脚跟到可接受高度，保持30秒（均匀呼吸不憋气）再轻轻放下。",
    purpose: "跟腱疼痛时静态保持是最安全的负荷：撑满30秒才能真正抑制肌腱痛感，几秒钟只是动一下。",
    observe: "跟腱症状不逐次增加；当天晚些时候和第二天没有持续加重。",
    easier: "减小抬起高度或保持10秒。",
    harder: "保持30秒不变，缩短组间休息，再进入双脚慢速提踵。",
    dose: { sets: "2组", reps: "每组5次" },
    tags: ["achilles", "tendon-loading", "heel-raise", "isometric"],
    startPosition: "坐位",
  },
  {
    id: "ankle-band-heelraise", region: "ankle-foot", stage: 2,
    actions: ["heel-raise-standing"],
    title: "踝四方向弹力带抗阻与提踵",
    how: "按力量缺口选1～2个弹力带方向，再做双脚提踵。",
    purpose: "把弹力带抗阻和提踵拼在一节课里，一次补齐查出来的力量缺口。",
    observe: "动作来自踝足，膝和脚趾不过度代偿。",
    easier: "改为保持不动发力，或扶墙轻轻踮脚尖。",
    harder: "单脚提踵或加轻负重。",
    dose: { sets: "3组", reps: "每项每组10～15个" },
    tags: ["ankle-strength", "calf", "peroneal"],
    startPosition: "站立",
  },
  {
    id: "knee-step", region: "knee", stage: 4,
    actions: ["step-up", "step-down"],
    title: "低台阶上台与下台",
    how: "先练患侧上台，稳定后练患侧支撑慢慢下台。",
    purpose: "下楼梯是多数膝痛最难的一关。慢速下台阶专门练膝盖的“刹车”能力。",
    observe: "胯稳住，膝盖和脚尖同向，别突然掉下来。",
    easier: "降低台阶、增加扶持。",
    harder: "增加高度、连续次数或负重。",
    dose: { sets: "3组", reps: "每侧每组8个" },
    tags: ["step-up", "step-down", "stairs"],
    startPosition: "站立",
  },
  {
    id: "knee-standing-hip-flexion", region: "knee", stage: 3,
    actions: ["hip-hinge"],
    title: "站立屈髋（臀部向后）",
    how: "背对墙站立约一脚距离，膝盖微屈，臀部向后移动轻碰墙面，身体从髋部向前折叠，再用臀腿站起；熟练后离开墙面做。",
    purpose: "练“用髋不用膝”的动作模式——捡东西、坐下、下楼都靠它；碰墙是唯一能自己验证的反馈，膝盖疼的人最该重新学会。",
    observe: "髋膝踝方向一致，脚掌稳定，腰部不抢先弯曲；碰不到墙或腰先酸了，说明动作做成了弯腰。",
    easier: "减小臀部向后幅度，扶支撑。",
    harder: "增加折髋范围、轻负重或改单腿。",
    dose: { sets: "3组", reps: "每组10个" },
    tags: ["hip-hinge", "movement-pattern", "standing-hip-flexion", "stairs"],
    startPosition: "站立",
  },
  {
    id: "ankle-standing-hip-flexion", region: "ankle-foot", stage: 3,
    actions: ["hip-hinge"],
    title: "站立屈髋（臀部向后）",
    how: "背对墙站立约一脚距离，膝盖微屈，臀部向后移动轻碰墙面，身体从髋部向前折叠，再用臀腿站起；熟练后离开墙面做。",
    purpose: "学会用髋发力，踝膝少代偿——捡东西、上下坡都靠这个模式。",
    observe: "骨盆稳定，髋膝踝方向一致，脚掌保持接触地面；碰不到墙说明做成了弯腰。",
    easier: "臀部向后碰墙并扶住固定物。",
    harder: "增加范围、轻负重或改单腿屈髋。",
    dose: { sets: "3组", reps: "每组10个" },
    tags: ["hip-hinge", "standing-hip-flexion", "posterior-chain", "hip-knee-ankle"],
    startPosition: "站立",
  },
  {
    id: "thigh-hip-hinge", region: "thigh-local", stage: 3,
    actions: ["hip-hinge"],
    title: "站立屈髋（臀部向后）",
    how: "背对墙站立约一脚距离，臀部向后移动轻碰墙面，躯干随之向前，再用臀腿力量站直；熟练后离开墙面做。",
    purpose: "学会用髋分担大腿后侧的压力，弯腰搬东西不再靠拉伤过的肌肉硬扛。",
    observe: "脊柱保持稳定，髋膝踝方向自然；碰不到墙说明做成了弯腰。",
    easier: "减小下移幅度，扶支撑。",
    harder: "增加轻负重。",
    dose: { sets: "3组", reps: "每组8～10个" },
    tags: ["hip-hinge", "hamstring", "posterior-chain"],
    startPosition: "站立",
  },
  {
    id: "ankle-gait-weightshift", region: "ankle-foot", stage: 3,
    actions: ["walk"],
    title: "重心转移与步态滚动",
    how: "先练双脚前后重心转移；慢走时只记两件事：脚跟先着地、脚趾最后离开。",
    purpose: "崴脚后人会不自觉避开患侧承重；把重心移回去、把落脚走顺，步态才算回归。",
    observe: "步幅自然，胯、髋、膝、踝一路连着动。",
    easier: "扶桌原地转移。",
    harder: "增加连续步数或不同速度。",
    dose: { sets: "3组", reps: "每组10次重心转移 + 10米步行" },
    tags: ["gait", "weight-shift", "hip-knee-ankle"],
    startPosition: "站立",
  },
  {
    id: "ankle-single-leg-step", region: "ankle-foot", stage: 4,
    actions: ["single-leg-stand", "step-up", "step-down"],
    title: "单腿站、提踵与台阶",
    how: "先单腿站，再单脚提踵和低台阶上下。",
    purpose: "单腿承重加台阶高度，把恢复的脚踝送回真实生活场景。",
    observe: "足弓、踝、膝和骨盆稳定，台阶下降可控。",
    easier: "扶墙、双脚提踵或降低台阶。",
    harder: "增加高度、连续次数或轻负重。",
    dose: { sets: "3组", reps: "每项每侧8个" },
    tags: ["single-leg", "heel-raise", "step"],
    startPosition: "站立",
  },
];

export const TRAINING_BY_ID = new Map(TRAINING_ENTRIES.map((entry) => [entry.id, entry]));
