import type { TrainingEntry } from "./types.ts";

export const TRAINING_ENTRIES: TrainingEntry[] = [
  {
    id: "knee-calf-raise", region: "knee", stage: 2,
    actions: ["heel-raise-standing"],
    title: "扶墙双脚提踵",
    how: "双手轻扶墙，脚跟垂直抬起，停1秒后缓慢落下。",
    purpose: "小腿力量回来了，走路蹬地才有劲，站立时膝盖也更稳。",
    observe: "两侧高度接近，膝盖保持稳定，脚踝不向内外倒。",
    easier: "坐姿提踵或减少高度。",
    harder: "单脚提踵或增加轻负重。",
    dose: { sets: "3组", reps: "每组10～15个" },
    tags: ["calf", "heel-raise", "gait"],
    startPosition: "站立",
  },
  {
    id: "calf-back-standing-raise", region: "calf-local", stage: 2,
    actions: ["heel-raise-standing"],
    title: "双脚站姿提踵",
    how: "扶墙站立，两侧脚跟同时抬起，再缓慢落下。",
    purpose: "站直提踵练腓肠肌，蹬地推进的力量从这里开始回到走路里。",
    observe: "两侧高度接近，不向内外歪。",
    easier: "回到坐姿提踵。",
    harder: "进阶单脚提踵。",
    dose: { sets: "3组", reps: "每组10～15个" },
    tags: ["calf-back", "gastrocnemius", "heel-raise"],
    startPosition: "站立",
  },
  {
    id: "calf-medial-arch", region: "calf-local", stage: 2,
    actions: ["heel-raise-standing"],
    title: "足弓保持与提踵",
    how: "站稳，脚趾放松贴地，轻轻踮脚尖再放下。",
    purpose: "小腿内侧和足弓一起练回来，走路时力量才不从小腿内侧漏掉。",
    observe: "脚趾不抠地，脚跟不向外甩，小腿不跟着转。",
    easier: "扶着墙做，只抬一点点。",
    harder: "增加提踵高度。",
    dose: { sets: "3组", reps: "每组10～15个" },
    tags: ["calf-medial", "arch", "heel-raise"],
    startPosition: "站立",
  },
  {
    id: "calf-back-seated-raise", region: "calf-local", stage: 1,
    actions: ["heel-raise-seated"],
    title: "坐姿提踵",
    how: "坐稳，前脚掌踩地，缓慢抬起脚跟再放下。",
    purpose: "膝盖弯着时比目鱼肌才肯出力——这是伤后最早能做的安全负荷。",
    observe: "小腿后侧发力，节奏稳定。",
    easier: "减小高度或个数。",
    harder: "膝上增加轻负重。",
    dose: { sets: "3组", reps: "每组8～12个" },
    tags: ["calf-back", "soleus", "heel-raise"],
    startPosition: "坐位",
  },
  {
    id: "ankle-achilles-isometric", region: "ankle-foot", stage: 1,
    actions: ["heel-raise-hold"],
    title: "坐姿提踵保持",
    how: "坐稳，前脚掌踩地，缓慢抬起脚跟到可接受高度，保持30秒（均匀呼吸不憋气）再轻轻放下。",
    purpose: "跟腱疼痛时静态保持是最安全的负荷：撑满30秒才能真正抑制肌腱痛感，几秒钟只是动一下。",
    observe: "跟腱症状不逐次增加；当天晚些时候和第二天没有持续加重。",
    easier: "减小抬起高度或保持10秒。",
    harder: "保持30秒不变，缩短组间休息，再进入双脚慢速提踵。",
    dose: { sets: "2组", reps: "每组5次" },
    tags: ["achilles", "tendon-loading", "heel-raise", "isometric"],
    startPosition: "坐位",
  },
  {
    id: "ankle-band-heelraise", region: "ankle-foot", stage: 2,
    actions: ["heel-raise-standing"],
    title: "踝四方向弹力带抗阻与提踵",
    how: "按力量缺口选1～2个弹力带方向，再做双脚提踵。",
    purpose: "把弹力带抗阻和提踵拼在一节课里，一次补齐查出来的力量缺口。",
    observe: "动作来自踝足，膝和脚趾不过度代偿。",
    easier: "改为保持不动发力，或扶墙轻轻踮脚尖。",
    harder: "单脚提踵或加轻负重。",
    dose: { sets: "3组", reps: "每项每组10～15个" },
    tags: ["ankle-strength", "calf", "peroneal"],
    startPosition: "站立",
  },
];

export const TRAINING_BY_ID = new Map(TRAINING_ENTRIES.map((entry) => [entry.id, entry]));
