import type { TrainingEntry } from "./types.ts";

export const TRAINING_ENTRIES: TrainingEntry[] = [
  {
    id: "knee-calf-raise", region: "knee", stage: 2,
    actions: ["heel-raise-standing"],
    title: "扶墙双脚提踵",
    how: "双手轻扶墙，脚跟垂直抬起，停1秒后缓慢落下。",
    purpose: "小腿力量回来了，走路蹬地才有劲，站立时膝盖也更稳。",
    observe: "两侧高度接近，膝盖保持稳定，脚踝不向内外倒。",
    easier: "坐姿提踵或减少高度。",
    harder: "单脚提踵或增加轻负重。",
    dose: { sets: "3组", reps: "每组10～15个" },
    tags: ["calf", "heel-raise", "gait"],
    startPosition: "站立",
  },
  {
    id: "calf-back-standing-raise", region: "calf-local", stage: 2,
    actions: ["heel-raise-standing"],
    title: "双脚站姿提踵",
    how: "扶墙站立，两侧脚跟同时抬起，再缓慢落下。",
    purpose: "站直提踵练腓肠肌，蹬地推进的力量从这里开始回到走路里。",
    observe: "两侧高度接近，不向内外歪。",
    easier: "回到坐姿提踵。",
    harder: "进阶单脚提踵。",
    dose: { sets: "3组", reps: "每组10～15个" },
    tags: ["calf-back", "gastrocnemius", "heel-raise"],
    startPosition: "站立",
  },
  {
    id: "calf-medial-arch", region: "calf-local", stage: 2,
    actions: ["heel-raise-standing"],
    title: "足弓保持与提踵",
    how: "站稳，脚趾放松贴地，轻轻踮脚尖再放下。",
    purpose: "小腿内侧和足弓一起练回来，走路时力量才不从小腿内侧漏掉。",
    observe: "脚趾不抠地，脚跟不向外甩，小腿不跟着转。",
    easier: "扶着墙做，只抬一点点。",
    harder: "增加提踵高度。",
    dose: { sets: "3组", reps: "每组10～15个" },
    tags: ["calf-medial", "arch", "heel-raise"],
    startPosition: "站立",
  },
  {
    id: "calf-back-seated-raise", region: "calf-local", stage: 1,
    actions: ["heel-raise-seated"],
    title: "坐姿提踵",
    how: "坐稳，前脚掌踩地，缓慢抬起脚跟再放下。",
    purpose: "膝盖弯着时比目鱼肌才肯出力——这是伤后最早能做的安全负荷。",
    observe: "小腿后侧发力，节奏稳定。",
    easier: "减小高度或个数。",
    harder: "膝上增加轻负重。",
    dose: { sets: "3组", reps: "每组8～12个" },
    tags: ["calf-back", "soleus", "heel-raise"],
    startPosition: "坐位",
  },
  {
    id: "ankle-achilles-isometric", region: "ankle-foot", stage: 1,
    actions: ["heel-raise-hold"],
    title: "坐姿提踵保持",
    how: "坐稳，前脚掌踩地，缓慢抬起脚跟到可接受高度，保持30秒（均匀呼吸不憋气）再轻轻放下。",
    purpose: "跟腱疼痛时静态保持是最安全的负荷：撑满30秒才能真正抑制肌腱痛感，几秒钟只是动一下。",
    observe: "跟腱症状不逐次增加；当天晚些时候和第二天没有持续加重。",
    easier: "减小抬起高度或保持10秒。",
    harder: "保持30秒不变，缩短组间休息，再进入双脚慢速提踵。",
    dose: { sets: "2组", reps: "每组5次" },
    tags: ["achilles", "tendon-loading", "heel-raise", "isometric"],
    startPosition: "坐位",
  },
  {
    id: "ankle-band-heelraise", region: "ankle-foot", stage: 2,
    actions: ["heel-raise-standing"],
    title: "踝四方向弹力带抗阻与提踵",
    how: "按力量缺口选1～2个弹力带方向，再做双脚提踵。",
    purpose: "把弹力带抗阻和提踵拼在一节课里，一次补齐查出来的力量缺口。",
    observe: "动作来自踝足，膝和脚趾不过度代偿。",
    easier: "改为保持不动发力，或扶墙轻轻踮脚尖。",
    harder: "单脚提踵或加轻负重。",
    dose: { sets: "3组", reps: "每项每组10～15个" },
    tags: ["ankle-strength", "calf", "peroneal"],
    startPosition: "站立",
  },
  {
    id: "knee-step", region: "knee", stage: 4,
    actions: ["step-up", "step-down"],
    title: "低台阶上台与下台",
    how: "先练患侧上台，稳定后练患侧支撑慢慢下台。",
    purpose: "下楼梯是多数膝痛最难的一关。慢速下台阶专门练膝盖的“刹车”能力。",
    observe: "胯稳住，膝盖和脚尖同向，别突然掉下来。",
    easier: "降低台阶、增加扶持。",
    harder: "增加高度、连续次数或负重。",
    dose: { sets: "3组", reps: "每侧每组8个" },
    tags: ["step-up", "step-down", "stairs"],
    startPosition: "站立",
  },
  {
    id: "knee-standing-hip-flexion", region: "knee", stage: 3,
    actions: ["hip-hinge"],
    title: "站立屈髋（臀部向后）",
    how: "背对墙站立约一脚距离，膝盖微屈，臀部向后移动轻碰墙面，身体从髋部向前折叠，再用臀腿站起；熟练后离开墙面做。",
    purpose: "练“用髋不用膝”的动作模式——捡东西、坐下、下楼都靠它；碰墙是唯一能自己验证的反馈，膝盖疼的人最该重新学会。",
    observe: "髋膝踝方向一致，脚掌稳定，腰部不抢先弯曲；碰不到墙或腰先酸了，说明动作做成了弯腰。",
    easier: "减小臀部向后幅度，扶支撑。",
    harder: "增加折髋范围、轻负重或改单腿。",
    dose: { sets: "3组", reps: "每组10个" },
    tags: ["hip-hinge", "movement-pattern", "standing-hip-flexion", "stairs"],
    startPosition: "站立",
  },
  {
    id: "ankle-standing-hip-flexion", region: "ankle-foot", stage: 3,
    actions: ["hip-hinge"],
    title: "站立屈髋（臀部向后）",
    how: "背对墙站立约一脚距离，膝盖微屈，臀部向后移动轻碰墙面，身体从髋部向前折叠，再用臀腿站起；熟练后离开墙面做。",
    purpose: "学会用髋发力，踝膝少代偿——捡东西、上下坡都靠这个模式。",
    observe: "骨盆稳定，髋膝踝方向一致，脚掌保持接触地面；碰不到墙说明做成了弯腰。",
    easier: "臀部向后碰墙并扶住固定物。",
    harder: "增加范围、轻负重或改单腿屈髋。",
    dose: { sets: "3组", reps: "每组10个" },
    tags: ["hip-hinge", "standing-hip-flexion", "posterior-chain", "hip-knee-ankle"],
    startPosition: "站立",
  },
  {
    id: "thigh-hip-hinge", region: "thigh-local", stage: 3,
    actions: ["hip-hinge"],
    title: "站立屈髋（臀部向后）",
    how: "背对墙站立约一脚距离，臀部向后移动轻碰墙面，躯干随之向前，再用臀腿力量站直；熟练后离开墙面做。",
    purpose: "学会用髋分担大腿后侧的压力，弯腰搬东西不再靠拉伤过的肌肉硬扛。",
    observe: "脊柱保持稳定，髋膝踝方向自然；碰不到墙说明做成了弯腰。",
    easier: "减小下移幅度，扶支撑。",
    harder: "增加轻负重。",
    dose: { sets: "3组", reps: "每组10个" },
    tags: ["hip-hinge", "hamstring", "posterior-chain"],
    startPosition: "站立",
  },
  {
    id: "ankle-gait-weightshift", region: "ankle-foot", stage: 3,
    actions: ["walk"],
    title: "重心转移与步态滚动",
    how: "先练双脚前后重心转移；慢走时只记两件事：脚跟先着地、脚趾最后离开。",
    purpose: "崴脚后人会不自觉避开患侧承重；把重心移回去、把落脚走顺，步态才算回归。",
    observe: "步幅自然，胯、髋、膝、踝一路连着动。",
    easier: "扶桌原地转移。",
    harder: "增加连续步数或不同速度。",
    dose: { sets: "3组", reps: "每组10次重心转移 + 10米步行" },
    tags: ["gait", "weight-shift", "hip-knee-ankle"],
    startPosition: "站立",
  },
  {
    id: "ankle-single-leg-step", region: "ankle-foot", stage: 4,
    actions: ["single-leg-stand", "step-up", "step-down"],
    title: "单腿站、提踵与台阶",
    how: "先单腿站，再单脚提踵和低台阶上下。",
    purpose: "单腿承重加台阶高度，把恢复的脚踝送回真实生活场景。",
    observe: "足弓、踝、膝和骨盆稳定，台阶下降可控。",
    easier: "扶墙、双脚提踵或降低台阶。",
    harder: "增加高度、连续次数或轻负重。",
    dose: { sets: "3组", reps: "每项每侧8个" },
    tags: ["single-leg", "heel-raise", "step"],
    startPosition: "站立",
  },

  {
    id: "knee-heel-slide-quad-set", region: "knee", stage: 1,
    actions: [],
    title: "膝盖弯曲和伸直训练",
    how: "仰卧，脚跟贴床慢慢弯膝盖，弯到发紧处停10～15秒再放回；然后腿伸直，绷紧大腿把膝后压向床面，保持5秒后放松。",
    purpose: "弯曲靠“滑到紧处停住”一点点找回来；膝后下压练的是“绷直”这个开关——肿痛时大腿常常想绷绷不上，开关不修好，后面的力量练习都白练。",
    observe: "停在发紧的位置时不出现锐痛；膝后下压时大腿前侧能真正绷起来，臀部不会不自觉抬起。",
    easier: "减小滑动范围，膝后下压保持3秒。",
    harder: "在伸膝末端加上弹力带抗阻。",
    dose: { sets: "3组", reps: "每项每组10个" },
    tags: ["knee-rom", "quad-activation", "quadriceps", "terminal-extension"],
    startPosition: "仰卧",
  },
  {
    id: "knee-bridge", region: "knee", stage: 2,
    actions: [],
    title: "臀桥",
    how: "仰卧屈膝，轻收腹后抬起臀部，停1秒再缓慢落下。",
    purpose: "让臀部和大腿后侧接管发力，替膝盖分担压力，是起身、上楼和站稳的基础力量。",
    observe: "臀部和大腿后侧发力，腰部不向上顶。",
    easier: "减小高度或每组6个。",
    harder: "脚垫高或进阶单腿臀桥。",
    dose: { sets: "3组", reps: "每组10～12个" },
    tags: ["glute", "hamstring", "posterior-chain"],
    startPosition: "仰卧",
  },
  {
    id: "knee-single-leg-bridge", region: "knee", stage: 3,
    actions: [],
    title: "单腿臀桥",
    how: "先做一次稳定的双脚臀桥，再抬起一只脚，用另一侧臀部把骨盆抬起，停1秒后缓慢落下。",
    purpose: "练一条腿承重时两侧胯保持一样高、膝盖不打软，这是上下楼和慢跑前的必经台阶。",
    observe: "两侧胯高度一致（可拍10秒回看），主要由臀部和大腿后侧发力，腰部不过度顶起。",
    easier: "继续双脚臀桥，或只把一只脚轻轻离地。",
    harder: "增加次数，再进阶站立屈髋（臀部向后）。",
    dose: { sets: "3组", reps: "每侧每组6～10个" },
    tags: ["glute", "hamstring", "posterior-chain", "single-leg", "pelvic-stability"],
    startPosition: "仰卧",
  },
  {
    id: "knee-supine-adductor", region: "knee", stage: 2,
    actions: [],
    title: "仰卧夹枕",
    how: "仰卧屈膝，在两膝之间夹软枕，轻轻向内夹住3秒后放松。",
    purpose: "大腿内侧没劲，膝内侧的压力就更大。轻轻夹枕头是唤醒内侧肌肉，不刺激膝盖。",
    observe: "大腿内侧均匀发力，不用疼痛顶住。",
    easier: "减小夹力或每组6个。",
    harder: "进阶到坐位或桥式夹枕。",
    dose: { sets: "3组", reps: "每组8～12个" },
    tags: ["adductor", "medial-knee"],
    startPosition: "仰卧",
  },
  {
    id: "knee-side-abduction", region: "knee", stage: 2,
    actions: [],
    title: "侧卧髋外展",
    how: "侧卧，下侧腿屈曲保持稳定，上侧腿伸直并稍向后放，脚尖朝前，缓慢抬起再落下。",
    purpose: "臀中肌是膝盖的“方向盘”，它有力，走路时膝盖才不会往内扣。",
    observe: "骨盆不要向后翻，大腿外侧不过度抢力。",
    easier: "减小抬腿高度或每组6个。",
    harder: "增加次数或加入轻弹力带。",
    dose: { sets: "3组", reps: "每侧每组8～12个" },
    tags: ["glute", "glute-med", "hip-abduction", "pelvic-stability"],
    startPosition: "侧卧",
  },
  {
    id: "knee-hamstring-isometric", region: "knee", stage: 2,
    actions: [],
    title: "大腿后侧等长保持",
    how: "坐稳或仰卧屈膝，脚跟踩稳地面，保持脚不移动，轻轻向后拉地面并保持。",
    purpose: "大腿后侧和前侧是一对配合的肌肉，后侧肯发力，膝盖前侧负担就小。绷住不动，是在不磨损膝盖的前提下练它。",
    observe: "感受大腿后侧发力，膝内侧和膝后不要出现刺痛。",
    easier: "减小发力或每组6个。",
    harder: "增加保持时间，再做臀桥或站立屈髋。",
    dose: { sets: "3组", reps: "每侧每组8～10个，每次保持5秒" },
    tags: ["hamstring", "knee-flexion", "posterior-chain"],
    startPosition: "仰卧",
  },
  {
    id: "knee-supine-ankle-press", region: "knee", stage: 2,
    actions: [],
    title: "仰卧踝跖屈",
    how: "仰卧或半躺，用脚掌轻推弹力带向下压，缓慢回到原位。",
    purpose: "小腿是走路蹬地的发动机。先躺着用轻阻力找到发力感，膝盖不用承重。",
    observe: "小腿后侧发力，脚趾不要抓紧。",
    easier: "去掉弹力带，只做主动下压。",
    harder: "进阶到坐姿提踵，再到站立提踵。",
    dose: { sets: "3组", reps: "每组10～15个" },
    tags: ["calf", "heel-raise"],
    startPosition: "仰卧",
  },
  {
    id: "knee-anterior-lower-leg-control", region: "knee", stage: 2,
    actions: [],
    title: "踝背屈控制",
    how: "仰卧或坐稳，脚跟放地，缓慢把脚背向小腿方向勾起，再缓慢放下，全程只动脚踝。",
    purpose: "小腿前侧失控，走路落脚会“啪叽”砸地，冲击直接传膝盖。练缓慢勾脚、慢慢放脚。",
    observe: "脚背整体抬起，不只抬脚趾；小腿前侧发力，膝盖不跟着转。",
    easier: "减小范围，每组6个。",
    harder: "加入轻弹力带，或站立时练习脚跟着地后的缓慢放脚。",
    dose: { sets: "3组", reps: "每组10个" },
    tags: ["tibialis-anterior", "dorsiflexion", "knee-weight-bearing"],
    startPosition: "仰卧",
  },
  {
    id: "knee-sit-stand-squat", region: "knee", stage: 3,
    actions: [],
    title: "坐站与浅蹲",
    how: "从合适高度椅子坐站，进阶到不碰椅子的浅蹲。",
    purpose: "把前面练的肌肉放进真实动作里：坐站是最安全的下蹲替身，先找回膝盖受控弯曲的感觉。",
    observe: "髋膝踝同向、左右承重接近、下降可控。",
    easier: "提高椅子并扶手。",
    harder: "降低椅子或手持轻重量。",
    dose: { sets: "3组", reps: "每组10个" },
    tags: ["sit-to-stand", "squat", "movement-pattern"],
    startPosition: "坐位",
  },
  {
    id: "knee-drop-landing", region: "knee", stage: 4,
    actions: [],
    title: "低台阶踏下停 2 秒",
    how: "站在低台阶上，患侧脚慢慢踏下落地，膝盖微弯缓冲，落地后定住2秒不动，再借双脚帮助回到台阶。",
    purpose: "跳之前先学会落地那一下的“刹车”。从台阶踏下来是冲击最小、最稳的落地练法，定得住才有资格练跳。",
    observe: "膝盖不往内扣，落地轻没有“咚”的一声；出现锐痛或打软就退回台阶练习。",
    easier: "先在平地上练双脚缓冲屈膝落地。",
    harder: "增加台阶高度，或改为向前一步落地。",
    dose: { sets: "3组", reps: "每侧每组8个" },
    tags: ["landing", "single-leg", "deceleration", "control"],
    startPosition: "站立",
  },
  {
    id: "knee-single-leg-strength", region: "knee", stage: 4,
    actions: [],
    title: "分腿蹲与单腿屈髋",
    how: "前后站位做分腿蹲，再用手扶支撑练单腿屈髋。",
    purpose: "从双腿过渡到一条腿承重，让患侧膝盖能独立站稳、可控发力，为跑跳做准备。",
    observe: "前脚稳定，骨盆不旋转，患侧可控承重。",
    easier: "减小幅度或双手扶持。",
    harder: "增加负重或减少扶持。",
    dose: { sets: "3组", reps: "每侧每组8个" },
    tags: ["single-leg", "strength", "daily"],
    startPosition: "站立",
  },
  {
    id: "knee-jump-decelerate", region: "knee", stage: 5,
    actions: [],
    title: "跳跃落地与减速",
    how: "从双脚小跳落地开始，进阶到前向落地、单脚和变向。",
    purpose: "跳回来的关键不是跳多高，而是落地那一下膝盖不内扣、稳得住。先练“落地刹车”。",
    observe: "髋膝踝共同缓冲，每次落地都能稳定停住。",
    easier: "退回低台阶踏下停 2 秒或快速踮脚尖。",
    harder: "增加高度、速度、方向或专项组合。",
    dose: { sets: "4组", reps: "每组5个" },
    tags: ["jump", "landing", "change-direction"],
    startPosition: "站立",
  },
  {
    id: "ankle-four-way-motion", region: "ankle-foot", stage: 1,
    actions: [],
    title: "踝四方向活动",
    how: "仰卧或半躺，小腿放松，分别缓慢做勾脚、下压、脚掌向内转和向外转。",
    purpose: "伤后脚踝最先僵；四个方向都缓慢动一遍，是防粘连、恢复滑利最安全的一步。",
    observe: "小腿不跟着转，不硬顶肿胀或刺痛末端。",
    easier: "每组6个、减小幅度。",
    harder: "加入弹力带轻阻力。",
    dose: { sets: "3组", reps: "每个方向每组10个" },
    tags: ["ankle-rom"],
    startPosition: "仰卧",
  },
  {
    id: "ankle-achilles-eccentric-drop", region: "ankle-foot", stage: 2,
    actions: [],
    title: "台阶边缘缓慢下落",
    how: "前脚掌踩在台阶边缘，扶稳后缓慢把脚跟降到台阶面以下（心里数3秒），用健侧脚帮忙回到起点；直腿做一组、弯膝做一组交替进行。",
    purpose: "跟腱病康复里证据最扎实的负荷动作：慢慢落下，让肌腱在受力里一点点变强，比静态保持更接近走路蹬地的真实需求。",
    observe: "跟腱有酸胀的用力感但不出现锐痛；第二天没有持续加重。",
    easier: "先在平地上慢慢轻轻踮脚尖，再落下。",
    harder: "在专业人员指导下增加下落深度或手持轻负重。",
    dose: { sets: "3组", reps: "每组8～12个" },
    tags: ["achilles", "eccentric", "heel-raise", "tendon-loading"],
    startPosition: "站立",
  },
  {
    id: "ankle-bridge", region: "ankle-foot", stage: 2,
    actions: [],
    title: "臀桥",
    how: "仰卧屈膝，双脚稳定踩地，轻收腹后抬起臀部，停1秒再缓慢落下。",
    purpose: "臀和腿后侧有力，走路蹬地时脚踝分担的压力就小——恢复链从最上游开始。",
    observe: "两侧胯保持一样高（可对镜子看），臀部和大腿后侧发力，脚踝保持稳定。",
    easier: "减小抬起高度或每组6个。",
    harder: "能够稳定完成后进阶单腿臀桥。",
    dose: { sets: "3组", reps: "每组10个" },
    tags: ["glute-max", "hamstring", "posterior-chain", "pelvic-stability"],
    startPosition: "仰卧",
  },
  {
    id: "ankle-single-leg-bridge", region: "ankle-foot", stage: 3,
    actions: [],
    title: "单腿臀桥",
    how: "先完成双脚臀桥，再抬起一只脚，用另一侧臀部抬起骨盆。",
    purpose: "练一条腿承重时骨盆和支撑踝一起稳住，这是跑跳前的必经台阶。",
    observe: "两侧胯高度一致（可拍10秒回看），支撑脚稳定，不用腰部顶起。",
    easier: "继续双脚臀桥，或只把一只脚轻轻离地。",
    harder: "进阶站立屈髋（臀部向后）和重心转移。",
    dose: { sets: "3组", reps: "每侧每组6～10个" },
    tags: ["glute-max", "hamstring", "posterior-chain", "single-leg", "pelvic-stability"],
    startPosition: "仰卧",
  },
  {
    id: "ankle-dorsiflexion-control", region: "ankle-foot", stage: 2,
    actions: [],
    title: "背屈控制（勾脚）",
    how: "仰卧或半躺，小腿放松，主动把脚背向小腿方向勾起；需要增加负荷时再加入轻弹力带。",
    purpose: "勾脚没劲会拖步绊脚；先把主动勾脚的控制找回来，迈步才利索。",
    observe: "脚踝带动，不只抬脚趾；小腿不向外转。",
    easier: "先做无阻力，每组6～8个。",
    harder: "进阶到坐位弹力带，再到站立脚跟走的短距离控制。",
    dose: { sets: "3组", reps: "每组10～15个" },
    tags: ["tibialis-anterior", "dorsiflexion", "ankle-dorsiflexor"],
    startPosition: "仰卧",
  },
  {
    id: "ankle-plantarflexion-control", region: "ankle-foot", stage: 2,
    actions: [],
    title: "跖屈控制（下压脚背）",
    how: "仰卧或半躺，脚掌轻推弹力带做向下压脚背；能稳定完成后再进阶坐姿提踵。",
    purpose: "下压脚背练的是蹬地发动机——走路最后那一下推进全靠它。",
    observe: "动作来自脚踝，脚趾不过度抓地。",
    easier: "去掉弹力带，只做主动下压。",
    harder: "进阶到坐姿、扶墙双脚提踵，再到单脚提踵。",
    dose: { sets: "3组", reps: "每组10～15个" },
    tags: ["calf", "plantarflexion", "heel-raise", "ankle-calf"],
    startPosition: "仰卧",
  },
  {
    id: "ankle-eversion-control", region: "ankle-foot", stage: 2,
    actions: [],
    title: "外翻控制",
    how: "仰卧或半躺，小腿不动，先做脚掌向外转；能稳定完成后再加入轻弹力带。",
    purpose: "外翻肌是脚踝的“防崴弹簧”；崴脚后它最先偷懒，也最该先练回来。",
    observe: "动作来自脚踝，不用膝盖或整条小腿向外转。",
    easier: "去掉弹力带，只做小幅主动外翻。",
    harder: "进阶到坐位弹力带，再进入单腿站和侧向控制。",
    dose: { sets: "3组", reps: "每组10～15个" },
    tags: ["peroneal", "eversion", "ankle-evertor"],
    startPosition: "仰卧",
  },
  {
    id: "ankle-split-squat-deceleration", region: "ankle-foot", stage: 4,
    actions: [],
    title: "分腿蹲与减速",
    how: "做分腿蹲和前跨一步后稳定停住，训练下肢协同承重。",
    purpose: "练“前冲之后刹得住”，防止跑步变向时脚踝再次受伤。",
    observe: "脚内侧别塌，髋、膝、踝一起缓冲，脚踝的练习不能被髋部练习顶替。",
    easier: "减小幅度并扶墙。",
    harder: "增加负重或侧向跨步。",
    dose: { sets: "3组", reps: "每侧每组8个" },
    tags: ["lower-chain", "deceleration"],
    startPosition: "站立",
  },
  {
    id: "ankle-hop-change-direction", region: "ankle-foot", stage: 5,
    actions: [],
    title: "快提踵、跳跃与变向",
    how: "从快节律双脚提踵、双脚小跳，进阶到单脚落地、侧跳和变向。",
    purpose: "跳、落、变向是回归运动的验收考：落地稳、踝不软才算过关。",
    observe: "每次落地稳定，踝不打软，髋膝踝连续吸收和释放力量。",
    easier: "回到慢提踵或双脚小幅落地。",
    harder: "增加速度、距离、方向或专项组合。",
    dose: { sets: "4组", reps: "每组5个" },
    tags: ["hop", "landing", "change-direction", "sport"],
    startPosition: "站立",
  },
  {
    id: "thigh-front-isometric", region: "thigh-local", stage: 1,
    actions: [],
    title: "大腿前侧绷紧保持",
    how: "仰卧或坐稳，把膝盖绷直，让大腿前侧收紧后放松。",
    purpose: "受伤后大腿前侧会“断电”性变懒，先躺着找回绷紧的感觉，是所有站立训练的地基。",
    observe: "两侧发力接近，症状不逐次增加。",
    easier: "减小用力或保持3秒。",
    harder: "增加到每组8次。",
    dose: { sets: "2组", reps: "每组5次，每次5秒" },
    tags: ["thigh-front", "quadriceps", "isometric"],
    startPosition: "仰卧",
  },
  {
    id: "thigh-front-extension-control", region: "thigh-local", stage: 2,
    actions: [],
    title: "坐姿伸膝控制",
    how: "坐稳，缓慢把小腿抬起到舒适范围，再慢慢放下。",
    purpose: "小腿能稳稳抬起再放下，膝盖才受得住上下楼和蹲起。",
    observe: "膝盖朝前，抬起和放下都能控制。",
    easier: "减小抬起范围。",
    harder: "增加停留或轻阻力。",
    dose: { sets: "3组", reps: "每组8～10个" },
    tags: ["thigh-front", "quadriceps", "knee-extension"],
    startPosition: "坐位",
  },
  {
    id: "thigh-back-isometric", region: "thigh-local", stage: 1,
    actions: [],
    title: "大腿后侧等长保持",
    how: "坐稳，脚跟踩地，像要把脚跟拖向椅子下方，但脚不要真的移动。",
    purpose: "大腿后侧参与稳住膝盖；坐着绷住不动，是拉伤后最安全的不牵拉发力。",
    observe: "大腿后侧均匀发力，不抽筋。",
    easier: "减小用力或保持3秒。",
    harder: "增加到每组8次。",
    dose: { sets: "2组", reps: "每组5次，每次5秒" },
    tags: ["thigh-back", "hamstring", "isometric"],
    startPosition: "坐位",
  },
  {
    id: "thigh-bridge", region: "thigh-local", stage: 2,
    actions: [],
    title: "臀桥",
    how: "仰卧屈膝，脚跟踩地，抬起臀部再缓慢落下。",
    purpose: "让臀和大腿后侧接管发力，受伤的大腿不用一直替全身扛活。",
    observe: "两侧胯保持一样高（可对镜子看），腰部不过度顶起。",
    easier: "减小高度。",
    harder: "进阶单腿臀桥。",
    dose: { sets: "3组", reps: "每组8～10个" },
    tags: ["thigh-back", "hamstring", "glute"],
    startPosition: "仰卧",
  },
  {
    id: "thigh-medial-isometric", region: "thigh-local", stage: 1,
    actions: [],
    title: "夹枕保持",
    how: "仰卧屈膝，在两膝之间放软枕，轻轻夹住后放松。",
    purpose: "大腿内侧没劲，膝盖就会晃；夹枕头是不摩擦关节的唤醒法。",
    observe: "大腿内侧均匀发力，不出现刺痛。",
    easier: "减小夹力或保持3秒。",
    harder: "增加到每组8次。",
    dose: { sets: "2组", reps: "每组5次，每次5秒" },
    tags: ["thigh-medial", "adductor", "isometric"],
    startPosition: "仰卧",
  },
  {
    id: "thigh-medial-active", region: "thigh-local", stage: 2,
    actions: [],
    title: "侧向收腿控制",
    how: "站稳并扶住固定物，把一侧腿从外侧缓慢收回身体中线。",
    purpose: "把内侧力量放进真实收腿动作里，变向、夹球时不再容易拉伤。",
    observe: "骨盆不转，收回过程平稳。",
    easier: "减小移动范围。",
    harder: "增加轻阻力。",
    dose: { sets: "3组", reps: "每组8～10个" },
    tags: ["thigh-medial", "adductor", "control"],
    startPosition: "站立",
  },
  {
    id: "thigh-lateral-isometric", region: "thigh-local", stage: 1,
    actions: [],
    title: "侧向抬腿保持",
    how: "扶墙站稳，把腿小幅向外抬起并保持，脚尖朝前。",
    purpose: "臀中肌是骨盆的“水平仪”，先静力练它，走路单腿支撑期才不晃。",
    observe: "躯干不侧倒，两侧胯保持一样高。",
    easier: "减小抬腿范围或时间。",
    harder: "增加到每组8次。",
    dose: { sets: "2组", reps: "每组5次，每次5秒" },
    tags: ["thigh-lateral", "glute-med", "isometric"],
    startPosition: "站立",
  },
  {
    id: "thigh-lateral-stability", region: "thigh-local", stage: 2,
    actions: [],
    title: "单腿骨盆稳定",
    how: "扶住固定物单腿站立，保持两侧骨盆大致水平。",
    purpose: "单腿站得稳，跑步的每一步才有地基；骨盆一歪，代偿就往上走。",
    observe: "支撑腿稳定，身体不明显侧倒；可手搭两侧胯骨或拍10秒视频回看。",
    easier: "双手扶稳并缩短时间。",
    harder: "减少扶持或加入轻微重心移动。",
    dose: { sets: "3组", reps: "每侧20～30秒" },
    tags: ["thigh-lateral", "glute-med", "single-leg"],
    startPosition: "站立",
  },
  {
    id: "thigh-sit-stand", region: "thigh-local", stage: 3,
    actions: [],
    title: "坐下再站起",
    how: "从稳固椅子缓慢坐下，再均匀用双腿站起。",
    purpose: "坐站是最安全的“功能性深蹲”，把练的力量直接接回日常生活。",
    observe: "左右用力接近，膝盖朝向脚尖。",
    easier: "提高椅子并扶手。",
    harder: "降低椅子或轻负重。",
    dose: { sets: "3组", reps: "每组8～10个" },
    tags: ["thigh-front", "thigh-medial", "sit-to-stand", "daily"],
    startPosition: "站立",
  },
  {
    id: "thigh-lateral-step", region: "thigh-local", stage: 3,
    actions: [],
    title: "侧向迈步",
    how: "膝髋微屈，向侧方小步移动，再缓慢回到起点。",
    purpose: "侧向移动考验大腿内外侧协同，是回归跑跳变向前的中间台阶。",
    observe: "骨盆保持稳定，双脚不过度内扣。",
    easier: "缩小步幅并扶稳。",
    harder: "增加轻阻力带。",
    dose: { sets: "3组", reps: "每侧8～10步" },
    tags: ["thigh-lateral", "thigh-medial", "lateral-step"],
    startPosition: "站立",
  },
  {
    id: "thigh-step", region: "thigh-local", stage: 4,
    actions: [],
    title: "台阶与单腿控制",
    how: "从低台阶上台开始，再练慢速下台。",
    purpose: "台阶把力量送进真实的高度变化，为下楼和跑步做准备。",
    observe: "症状可控，骨盆和膝足稳定。",
    easier: "降低台阶。",
    harder: "增加高度。",
    dose: { sets: "3组", reps: "每侧6～8个" },
    tags: ["step", "single-leg"],
    startPosition: "站立",
  },
  {
    id: "thigh-run-return", region: "thigh-local", stage: 5,
    actions: [],
    title: "跑步与变速回归",
    how: "从走跑交替逐步增加连续跑，再进入加速或变向。",
    purpose: "冲刺和变向是拉伤复发的高危场景，一次只加一项负荷才能安全回归。",
    observe: "无锐痛，动作稳定，次日反应可接受。",
    easier: "缩短慢跑。",
    harder: "一次只增加速度、时间或变向中的一项。",
    dose: { sets: "3～4组", reps: "每组20～30秒" },
    tags: ["run", "sport"],
    startPosition: "站立",
  },
  {
    id: "calf-front-active", region: "calf-local", stage: 1,
    actions: [],
    title: "主动勾脚",
    how: "坐稳，脚跟放地，把脚背向小腿方向勾起，再缓慢放下。",
    purpose: "小腿前侧是走路的“抬脚刹车”，它没劲会拖步绊脚，先练主动勾抬。",
    observe: "脚背整体抬起，不只抬脚趾。",
    easier: "减小范围。",
    harder: "增加到每组15个。",
    dose: { sets: "2组", reps: "每组6～10个" },
    tags: ["calf-front", "dorsiflexion"],
    startPosition: "坐位",
  },
  {
    id: "calf-front-endurance", region: "calf-local", stage: 2,
    actions: [],
    title: "脚跟走耐力",
    how: "扶稳后轻抬前脚掌，用脚跟小步向前走。",
    purpose: "脚跟走把勾脚力量变成耐力，下台阶和落地时不再啪叽砸地。",
    observe: "脚尖能持续抬起，不拖地。",
    easier: "原地交替勾脚。",
    harder: "增加步数。",
    dose: { sets: "3组", reps: "每组10～15步" },
    tags: ["calf-front", "dorsiflexion", "gait"],
    startPosition: "站立",
  },
  {
    id: "calf-medial-active", region: "calf-local", stage: 1,
    actions: [],
    title: "小幅内翻控制",
    how: "坐稳，小腿不动，把脚掌小幅向内转，再缓慢回正。",
    purpose: "内翻控制差，足弓会塌着受力；先小幅无阻力找回脚踝内侧的发力感。",
    observe: "动作来自脚踝，膝盖不跟着转。",
    easier: "减小范围。",
    harder: "用另一只脚增加轻阻力。",
    dose: { sets: "2组", reps: "每组6～10个" },
    tags: ["calf-medial", "inversion"],
    startPosition: "坐位",
  },
  {
    id: "calf-lateral-active", region: "calf-local", stage: 1,
    actions: [],
    title: "小幅外翻控制",
    how: "坐稳，小腿不动，把脚掌小幅向外转，再缓慢回正。",
    purpose: "外侧腓骨肌是“防崴弹簧”，崴过脚的人必须把它练回来。",
    observe: "膝盖不跟着转，动作不靠甩动。",
    easier: "减小范围。",
    harder: "增加轻阻力。",
    dose: { sets: "2组", reps: "每组6～10个" },
    tags: ["calf-lateral", "eversion"],
    startPosition: "坐位",
  },
  {
    id: "calf-lateral-stability", region: "calf-local", stage: 2,
    actions: [],
    title: "单腿外侧稳定",
    how: "扶稳后单腿站立，保持足底三点支撑和脚踝稳定。",
    purpose: "单腿站练脚踝的动态稳定，走不平的路才不心里发虚。",
    observe: "脚踝不反复向外翻，身体不过度摇晃；可拍10秒视频回看落地侧。",
    easier: "双手扶稳并缩短时间。",
    harder: "减少扶持或轻微移动重心。",
    dose: { sets: "3组", reps: "每侧20～30秒" },
    tags: ["calf-lateral", "eversion", "single-leg"],
    startPosition: "站立",
  },
  {
    id: "calf-gait", region: "calf-local", stage: 3,
    actions: [],
    title: "重心转移与走路",
    how: "先练原地重心转移；走路时只记两件事：脚跟先着地、脚趾最后离开。",
    purpose: "伤后人会不自觉避开患侧承重；把落脚走顺，步态才算真正回归。",
    observe: "步幅自然，不跛行。",
    easier: "扶桌小幅转移。",
    harder: "增加步数或速度。",
    dose: { sets: "3组", reps: "每组10次，再走10米" },
    tags: ["gait"],
    startPosition: "站立",
  },
  {
    id: "calf-step-single-leg", region: "calf-local", stage: 4,
    actions: [],
    title: "台阶与单腿稳定",
    how: "先单腿站，再做低台阶上下。",
    purpose: "台阶把小腿送回高负荷场景，为跑跳做最后准备。",
    observe: "症状可控，髋膝踝协同。",
    easier: "扶墙并降低台阶。",
    harder: "增加高度。",
    dose: { sets: "3组", reps: "每侧6～8个" },
    tags: ["step", "single-leg"],
    startPosition: "站立",
  },
  {
    id: "calf-run-hop", region: "calf-local", stage: 5,
    actions: [],
    title: "跑跳与蹬地回归",
    how: "从走跑交替、快提踵进入小幅双脚跳。",
    purpose: "提踵弹跳是回归运动的验收考：落地稳、蹬地有力才算过关。",
    observe: "无锐痛，次日反应可接受。",
    easier: "回到快走。",
    harder: "一次只增加一项负荷。",
    dose: { sets: "3～4组", reps: "每组5次或20秒" },
    tags: ["run", "hop"],
    startPosition: "站立",
  },
];

export const TRAINING_BY_ID = new Map(TRAINING_ENTRIES.map((entry) => [entry.id, entry]));
