// Presentation stages import domain vocabulary through this facade. The workbench
// remains the owner of state transitions, persistence, and workflow commands.
export { currentComplaintText, extractComplaintPrioritySide } from "@/src/domain/rehab/intake/intake-complaint-core";
export { emptyCapabilities } from "@/src/domain/rehab/intake/workflow-profile-core";
export type { CapabilityKey, OperationTarget, ProductMode, WorkflowProfile } from "@/src/domain/rehab/intake/workflow-profile-core";
export { chiefActionLabel, chiefMotionDirectionId, chiefMotionDirectionIds, hasClearChiefAction, isAcuteTrauma, primaryReportedAction, reportedActionSummary } from "@/src/domain/rehab/intake/chief-action-core";
export { includesAny } from "@/src/domain/rehab/treatment/candidate-order-core";
export { resultFromScore } from "@/src/domain/rehab/treatment/trial-record-builder";
export type { CompletedRangeRetestAnswer, RangeRetestAnswer, TrialRecord, TrialResult, YesNo } from "@/src/domain/rehab/treatment/trial-record-types";
export { shouldAskMotionDiscomfort, shouldAskPairedStrength, shouldCaptureUnableMotionSymptom, strengthAnswerResult } from "@/src/domain/rehab/assessment/assessment-answer-core";
export type { StrengthUnableReason } from "@/src/domain/rehab/assessment/assessment-answer-core";
export { actionIdFromFinding, anyMotionIdFromFinding, canonicalActionIdFromAssessmentId, dedupeAssessmentIdsByAction, dedupeRetestFindingsByAction, motionIdFromFinding, motionWasSymptomatic, samePhysicalAction, valueForPhysicalAction } from "@/src/domain/rehab/intake/action-identity-core";
export { adverseCaptureComplete } from "@/src/domain/rehab/followup/adverse-response-core";
export type { AdverseResolution, AdverseResponseEvent, AdverseSource, AdverseTiming } from "@/src/domain/rehab/followup/adverse-response-core";
export { buildFindingGroups } from "@/src/domain/rehab/shared/finding-groups-core";
export { functionCompletionValue, functionControlValue, functionDiscomfortValue } from "@/src/domain/rehab/assessment/function-assessment-core";
export { motionNeedsPassive } from "@/src/domain/rehab/assessment/motion-assessment-core";
export { assessmentRecordComplete } from "@/src/domain/rehab/assessment/assessment-record-complete-core";
export type { BilateralPriorityResolution, BilateralSide, BilateralTrainingGate } from "@/src/domain/rehab/shared/bilateral-flow-core";
export { bilateralCheckpointOptions } from "@/src/domain/rehab/shared/bilateral-flow-core";
export type { TissuePathwayDecision } from "@/src/domain/rehab/safety/tissue-pathway-core";
export { summarizeTreatmentCoverage } from "@/src/domain/rehab/treatment/treatment-coverage-core";
export { chiefChangeExplanation } from "@/src/domain/rehab/retest/chief-change-explanation-core";
export { assessmentGapActionLabel } from "@/src/domain/rehab/assessment/assessment-gap-core";
export { skippedChiefActionTitles } from "@/src/domain/rehab/assessment/function-assessment-plan-core";
export type { AssessmentGap } from "@/src/domain/rehab/assessment/assessment-gap-core";
export { nextRangeCandidateType } from "@/src/domain/rehab/retest/retest-routing-core";
export { candidateTreatmentKey, candidateTreatmentName } from "@/src/domain/rehab/treatment/candidate-treatment-core";
export { candidateAction } from "@/src/domain/rehab/treatment/candidate-action-core";
export { functionEvidenceFromRecord } from "@/src/domain/rehab/retest/function-evidence-core";
export { resolveTreatmentRetestGate } from "@/src/domain/rehab/retest/function-retest-transition-core";
export { canReuseLatestRetest, canReuseLatestRetest as canReuseLatestRetestDecision } from "@/src/domain/rehab/retest/retest-reuse-core";
export type { PendingQueueAdvance } from "@/src/domain/rehab/shared/workflow-state-core";
export type { LocalLimbDecision } from "@/src/domain/rehab/shared/local-limb-decision-core";
export type { LedgerEntry } from "@/src/domain/rehab/shared/problem-ledger-core";
export type { RetestEligibility } from "@/src/domain/rehab/retest/retest-eligibility-core";
export type { KneeAssessmentCheck } from "@/src/domain/rehab/shared/knee-decision-core";
export { needsTrainingToleranceRetest, needsTreatmentFinalChiefRetest, treatmentMustStop } from "@/src/domain/rehab/treatment/treatment-session-core";
export { pendingTrainingFeedback, trainingFeedbackComplete } from "@/src/domain/rehab/training/training-feedback-core";
export { planQuickFeedbackRecord } from "@/src/domain/rehab/training/training-feedback-core";
export type { HomeRelaxationTarget } from "@/src/domain/rehab/training/home-relaxation-core";
export { resolvedTreatmentCombination, treatmentResponsePriority } from "@/src/domain/rehab/treatment/treatment-response-core";
export { formatRecommendedDateRange, recommendNextSession } from "@/src/domain/rehab/followup/next-session-recommendation-core";
export { compareFollowupScore } from "@/src/domain/rehab/followup/followup-review-core";
export { markingSideMismatchHint } from "@/src/domain/rehab/shared/marking-side-consistency-core";
export { descriptionSuggestsTraumaText, traumaMechanismMismatchHint } from "@/src/domain/rehab/intake/trauma-mechanism-consistency-core";
