import type {
  ActionDefinition,
  AssessmentDefinition,
  ComplaintBranch,
  KnowledgeReviewPackage,
  KnowledgeSourceCase,
  RecordedTime,
  SourceDocument,
  SourceRef,
} from "./contracts.ts";

const notRecorded = { status: "not-recorded" } as const;

function recorded(value: string): RecordedTime {
  return { status: "explicit", value };
}

function sourceRef(documentId: string, locator: string): SourceRef {
  return { documentId, locator };
}

function rawDocument(id: string, sourceLocator: string): SourceDocument {
  return { id, collectionId: "COL-AI-RAW", kind: "raw-record", sourceLocator };
}

const actionDefinitions: ActionDefinition[] = [
  { id: "squat", label: "下蹲", roles: ["complaint", "assessment", "retest"], use: "conditional-assessment", sourceCaseIds: ["RAW-KNEE-001", "RAW-KNEE-002", "RAW-KNEE-008"] },
  { id: "knee-flexion-end-range", label: "弯膝到末端", roles: ["complaint", "assessment", "retest"], use: "branch-assessment", sourceCaseIds: ["RAW-KNEE-002", "RAW-KNEE-005"] },
  { id: "step-down", label: "下台阶", roles: ["complaint", "assessment", "retest"], use: "branch-assessment", sourceCaseIds: ["RAW-KNEE-003"] },
  { id: "patella-press", label: "轻按髌骨", roles: ["assessment", "retest"], use: "conditional-assessment", sourceCaseIds: ["RAW-KNEE-004"] },
  { id: "knee-extension", label: "主动绷直膝盖", roles: ["complaint", "assessment", "retest"], use: "branch-assessment", sourceCaseIds: ["RAW-KNEE-001", "RAW-KNEE-005"] },
  { id: "standing-knee-extension", label: "站直腿", roles: ["complaint", "assessment", "retest"], use: "conditional-assessment", sourceCaseIds: ["RAW-KNEE-006"] },
  { id: "knee-extension-press", label: "绷直膝盖并轻轻下压", roles: ["complaint", "assessment", "retest"], use: "conditional-assessment", sourceCaseIds: ["RAW-KNEE-001"] },
  { id: "knee-weight-bearing", label: "膝部承重", roles: ["complaint", "assessment", "retest"], use: "conditional-assessment", sourceCaseIds: ["RAW-KNEE-001"] },
  { id: "bird-dog-leg-extension", label: "鸟狗伸腿", roles: ["complaint", "assessment", "retest"], use: "source-record-only", sourceCaseIds: ["RAW-KNEE-007"] },
];

const assessmentDefinitions: AssessmentDefinition[] = [
  { id: "squat-symptom-reproduction", title: "下蹲时的膝部反应", kind: "symptom-reproduction", actionId: "squat", professionalOnly: false, sourceCaseIds: ["RAW-KNEE-001", "RAW-KNEE-008"] },
  { id: "squat-movement-observation", title: "下蹲动作表现", kind: "basic-movement", actionId: "squat", professionalOnly: false, sourceCaseIds: ["RAW-KNEE-002"] },
  { id: "knee-passive-flexion-end-range", title: "被动屈膝末端", kind: "local-motion", actionId: "knee-flexion-end-range", professionalOnly: true, sourceCaseIds: ["RAW-KNEE-002", "RAW-KNEE-005"] },
  { id: "knee-active-extension", title: "主动伸膝", kind: "local-motion", actionId: "knee-extension", professionalOnly: false, sourceCaseIds: ["RAW-KNEE-001", "RAW-KNEE-005"] },
  { id: "step-down-symptom-reproduction", title: "下台阶时的膝部反应", kind: "symptom-reproduction", actionId: "step-down", professionalOnly: false, sourceCaseIds: ["RAW-KNEE-003"] },
  { id: "patella-glide-and-pressure", title: "髌骨滑动与轻按反应", kind: "local-motion", actionId: "patella-press", professionalOnly: true, sourceCaseIds: ["RAW-KNEE-004"] },
  { id: "ankle-active-dorsiflexion", title: "脚踝主动背屈", kind: "local-motion", professionalOnly: false, sourceCaseIds: ["RAW-KNEE-004"] },
  { id: "ankle-active-eversion", title: "脚踝主动外翻", kind: "local-motion", professionalOnly: false, sourceCaseIds: ["RAW-KNEE-004"] },
  { id: "ankle-talus-fibula-mobility", title: "距骨与腓骨活动", kind: "local-motion", professionalOnly: true, sourceCaseIds: ["RAW-KNEE-004"] },
  { id: "lateral-thigh-response", title: "大腿外侧反应", kind: "muscle-response", professionalOnly: true, sourceCaseIds: ["RAW-KNEE-004"] },
  { id: "popliteus-response", title: "腘肌反应", kind: "muscle-response", professionalOnly: true, sourceCaseIds: ["RAW-KNEE-002"] },
  { id: "psoas-response", title: "腰大肌反应", kind: "muscle-response", professionalOnly: true, sourceCaseIds: ["RAW-KNEE-002"] },
  { id: "quadratus-lumborum-response", title: "腰方肌反应", kind: "muscle-response", professionalOnly: true, sourceCaseIds: ["RAW-KNEE-002"] },
  { id: "pelvis-active-movement", title: "骨盆主动活动", kind: "basic-movement", professionalOnly: true, sourceCaseIds: ["RAW-KNEE-002"] },
  { id: "knee-weight-bearing-symptom", title: "膝部承重时的反应", kind: "symptom-reproduction", actionId: "knee-weight-bearing", professionalOnly: false, sourceCaseIds: ["RAW-KNEE-001"] },
  { id: "knee-extension-press-symptom", title: "伸膝下压时的反应", kind: "symptom-reproduction", actionId: "knee-extension-press", professionalOnly: false, sourceCaseIds: ["RAW-KNEE-001"] },
  { id: "standing-knee-extension-symptom", title: "站直腿时的膝部反应", kind: "symptom-reproduction", actionId: "standing-knee-extension", professionalOnly: false, sourceCaseIds: ["RAW-KNEE-006"] },
  { id: "bird-dog-support-symptom", title: "鸟狗支撑时的膝部反应", kind: "symptom-reproduction", actionId: "bird-dog-leg-extension", professionalOnly: false, sourceCaseIds: ["RAW-KNEE-007"] },
];

const complaintBranches: ComplaintBranch[] = [
  {
    id: "knee-squat-pain-or-scraping",
    title: "下蹲时膝部疼痛、刮擦或弹响",
    bodyRegion: "knee",
    sourceCaseIds: ["RAW-KNEE-001", "RAW-KNEE-008"],
    initialAssessmentIds: ["squat-symptom-reproduction"],
    continuationAssessmentIds: [],
    safetyNotes: ["肿胀或近期受伤先完成安全确认。", "疼痛、刮擦和弹响分别记录，不能用一个结果覆盖其他表现。"],
  },
  {
    id: "knee-terminal-flexion-discomfort",
    title: "弯膝末端不舒服",
    bodyRegion: "knee",
    sourceCaseIds: ["RAW-KNEE-002", "RAW-KNEE-005"],
    initialAssessmentIds: ["knee-passive-flexion-end-range", "knee-active-extension", "popliteus-response"],
    continuationAssessmentIds: ["squat-movement-observation", "psoas-response", "quadratus-lumborum-response", "pelvis-active-movement"],
    safetyNotes: ["近期外翻等明确受伤机制先完成安全确认，再进入末端活动检查。"],
  },
  {
    id: "knee-step-down-posterior-discomfort",
    title: "下台阶时膝后不舒服",
    bodyRegion: "knee",
    sourceCaseIds: ["RAW-KNEE-003"],
    initialAssessmentIds: ["step-down-symptom-reproduction"],
    continuationAssessmentIds: [],
    safetyNotes: [],
  },
  {
    id: "knee-patella-pressure-pain",
    title: "髌骨滑动或轻按时疼",
    bodyRegion: "knee",
    sourceCaseIds: ["RAW-KNEE-004"],
    initialAssessmentIds: ["patella-glide-and-pressure", "lateral-thigh-response"],
    continuationAssessmentIds: ["ankle-active-dorsiflexion", "ankle-active-eversion", "ankle-talus-fibula-mobility"],
    safetyNotes: [],
  },
  {
    id: "knee-extension-medial-discomfort",
    title: "伸膝时膝内侧不舒服",
    bodyRegion: "knee",
    sourceCaseIds: ["RAW-KNEE-001", "RAW-KNEE-006"],
    initialAssessmentIds: ["knee-active-extension", "knee-extension-press-symptom", "standing-knee-extension-symptom"],
    continuationAssessmentIds: [],
    safetyNotes: [],
  },
  {
    id: "knee-weight-bearing-fullness",
    title: "膝部承重时发胀",
    bodyRegion: "knee",
    sourceCaseIds: ["RAW-KNEE-001"],
    initialAssessmentIds: ["knee-weight-bearing-symptom"],
    continuationAssessmentIds: [],
    safetyNotes: [],
  },
  {
    id: "knee-support-contact-pain",
    title: "膝部支撑接触时疼",
    bodyRegion: "knee",
    sourceCaseIds: ["RAW-KNEE-007"],
    initialAssessmentIds: ["bird-dog-support-symptom"],
    continuationAssessmentIds: [],
    safetyNotes: [],
  },
];

const sourceCases: KnowledgeSourceCase[] = [
  {
    id: "RAW-KNEE-001",
    reviewStatus: "awaiting-owner-review",
    sourceDocuments: [
      rawDocument("RAW-KNEE-001-D01", "2024.7.28治疗记录.txt:70-79"),
      rawDocument("RAW-KNEE-001-D02", "2024.7.30治疗记录.txt:96-102"),
      rawDocument("RAW-KNEE-001-D03", "2024.10.29治疗记录.txt:3-13"),
      rawDocument("RAW-KNEE-001-D04", "2024.10.31治疗记录.txt:28-48"),
    ],
    episodes: [
      {
        id: "RAW-KNEE-22F355F1B571",
        sessionDate: recorded("2024-07-28"),
        complaint: {
          branchId: "knee-weight-bearing-fullness",
          side: "left",
          rawSummary: "左膝承重时会胀；同期另有腰部紧酸。",
          symptomQualities: ["胀"],
          currentActionIds: ["knee-weight-bearing"],
          injuryActionIds: [],
          timing: { earliestOnset: notRecorded, latestOccurrence: recorded("2024-07-28 当次"), injuryEvent: notRecorded },
          sourceRef: sourceRef("RAW-KNEE-001-D01", "L71"),
        },
        findings: [{ id: "RAW-KNEE-001-E01-F01", assessmentId: "knee-weight-bearing-symptom", side: "left", finding: "承重时发胀", sourceRef: sourceRef("RAW-KNEE-001-D01", "L71") }],
        treatmentExperiments: [{
          id: "RAW-KNEE-001-E01-T01",
          findingIds: ["RAW-KNEE-001-E01-F01"],
          primaryTarget: "胫骨前肌与趾长伸肌主动控制组合",
          targetType: "movement-control",
          intervention: "同时激活胫骨前肌和趾长伸肌",
          attribution: "combined-targets",
          supportingInterventions: [],
          retestIds: ["RAW-KNEE-001-E01-R01"],
          sourceRef: sourceRef("RAW-KNEE-001-D01", "L71-L72"),
        }],
        retests: [{ id: "RAW-KNEE-001-E01-R01", treatmentExperimentId: "RAW-KNEE-001-E01-T01", actionId: "knee-weight-bearing", before: "承重时发胀", after: "缓解", result: "better", sourceRef: sourceRef("RAW-KNEE-001-D01", "L71") }],
        interventionsWithoutItemizedRetest: [{ id: "RAW-KNEE-001-E01-I01", relatedFindingIds: ["RAW-KNEE-001-E01-F01"], intervention: "同次另有神经松动、躯干与小腿区域处理，原文未逐项复查", note: "performed-without-itemized-retest", sourceRef: sourceRef("RAW-KNEE-001-D01", "L73-L78") }],
      },
      {
        id: "RAW-KNEE-2E9D4EC80CA5",
        sessionDate: recorded("2024-07-30"),
        complaint: {
          branchId: "knee-extension-medial-discomfort",
          side: "left",
          rawSummary: "左膝伸直时有刮擦感，同时记录左侧鹅足肌腱处不适。",
          symptomQualities: ["刮擦感", "不适"],
          currentActionIds: ["knee-extension"],
          injuryActionIds: [],
          timing: { earliestOnset: notRecorded, latestOccurrence: recorded("2024-07-30 当次"), injuryEvent: notRecorded },
          sourceRef: sourceRef("RAW-KNEE-001-D02", "L97"),
        },
        findings: [{ id: "RAW-KNEE-001-E02-F01", assessmentId: "knee-active-extension", side: "left", finding: "伸直时有刮擦感", sourceRef: sourceRef("RAW-KNEE-001-D02", "L97") }],
        treatmentExperiments: [{
          id: "RAW-KNEE-001-E02-T01",
          findingIds: ["RAW-KNEE-001-E02-F01"],
          primaryTarget: "趾长伸肌方向",
          targetType: "muscle",
          intervention: "松解并激活趾长伸肌",
          attribution: "single-target",
          supportingInterventions: [],
          retestIds: ["RAW-KNEE-001-E02-R01"],
          sourceRef: sourceRef("RAW-KNEE-001-D02", "L97-L100"),
        }],
        retests: [{ id: "RAW-KNEE-001-E02-R01", treatmentExperimentId: "RAW-KNEE-001-E02-T01", actionId: "knee-extension", before: "伸直时有刮擦感", after: "刮擦感缓解", result: "better", sourceRef: sourceRef("RAW-KNEE-001-D02", "L97") }],
        interventionsWithoutItemizedRetest: [{ id: "RAW-KNEE-001-E02-I01", relatedFindingIds: ["RAW-KNEE-001-E02-F01"], intervention: "同次另有髌骨活动、半腱肌处理和超声，原文未逐项复查", note: "performed-without-itemized-retest", sourceRef: sourceRef("RAW-KNEE-001-D02", "L98-L101") }],
      },
      {
        id: "RAW-KNEE-FAAEDDD75256",
        sessionDate: recorded("2024-10-29"),
        complaint: {
          branchId: "knee-squat-pain-or-scraping",
          side: "right",
          rawSummary: "右膝肿胀、上缘疼痛，先在靠墙滑蹲时发现，后来一般下蹲起身也会疼。",
          symptomQualities: ["肿胀", "疼痛"],
          currentActionIds: ["squat"],
          injuryActionIds: [],
          timing: { earliestOnset: notRecorded, latestOccurrence: recorded("2024-10-29 当次"), injuryEvent: notRecorded },
          sourceRef: sourceRef("RAW-KNEE-001-D03", "L4"),
        },
        findings: [{ id: "RAW-KNEE-001-E03-F01", assessmentId: "squat-symptom-reproduction", side: "right", finding: "下蹲起身时膝上缘疼痛", sourceRef: sourceRef("RAW-KNEE-001-D03", "L4") }],
        treatmentExperiments: [{
          id: "RAW-KNEE-001-E03-T01",
          findingIds: ["RAW-KNEE-001-E03-F01"],
          primaryTarget: "腓骨近端活动",
          targetType: "joint",
          intervention: "腓骨近端松动",
          attribution: "single-target",
          supportingInterventions: [],
          retestIds: ["RAW-KNEE-001-E03-R01"],
          sourceRef: sourceRef("RAW-KNEE-001-D03", "L4,L9"),
        }],
        retests: [{ id: "RAW-KNEE-001-E03-R01", treatmentExperimentId: "RAW-KNEE-001-E03-T01", actionId: "squat", before: "下蹲起身时疼", after: "缓解", result: "better", sourceRef: sourceRef("RAW-KNEE-001-D03", "L4") }],
        interventionsWithoutItemizedRetest: [{ id: "RAW-KNEE-001-E03-I01", relatedFindingIds: ["RAW-KNEE-001-E03-F01"], intervention: "同次另有大腿外侧、股直肌、腘肌、臀中肌及其他区域处理，原文未逐项复查", note: "performed-without-itemized-retest", sourceRef: sourceRef("RAW-KNEE-001-D03", "L5-L12") }],
      },
      {
        id: "RAW-KNEE-C06633F10CA4",
        sessionDate: recorded("2024-10-31"),
        complaint: {
          branchId: "knee-extension-medial-discomfort",
          side: "bilateral",
          rawSummary: "双膝内侧疼；当次可用左膝伸直下压复现内侧疼痛。原文中的结构解释未作为评估事实。",
          symptomQualities: ["疼痛"],
          currentActionIds: ["knee-extension-press"],
          injuryActionIds: [],
          timing: { earliestOnset: notRecorded, latestOccurrence: recorded("2024-10-31 当次"), injuryEvent: notRecorded },
          sourceRef: sourceRef("RAW-KNEE-001-D04", "L29,L34"),
        },
        findings: [{ id: "RAW-KNEE-001-E04-F01", assessmentId: "knee-extension-press-symptom", side: "left", finding: "伸直下压时内侧疼痛", sourceRef: sourceRef("RAW-KNEE-001-D04", "L34") }],
        treatmentExperiments: [{
          id: "RAW-KNEE-001-E04-T01",
          findingIds: ["RAW-KNEE-001-E04-F01"],
          primaryTarget: "足外翻主动控制",
          targetType: "movement-control",
          intervention: "促进足外翻后再次伸膝下压",
          attribution: "single-target",
          supportingInterventions: [],
          retestIds: ["RAW-KNEE-001-E04-R01"],
          sourceRef: sourceRef("RAW-KNEE-001-D04", "L34"),
        }],
        retests: [{ id: "RAW-KNEE-001-E04-R01", treatmentExperimentId: "RAW-KNEE-001-E04-T01", actionId: "knee-extension-press", before: "内侧疼痛", after: "疼痛消失", result: "better", sourceRef: sourceRef("RAW-KNEE-001-D04", "L34") }],
        interventionsWithoutItemizedRetest: [{ id: "RAW-KNEE-001-E04-I01", relatedFindingIds: ["RAW-KNEE-001-E04-F01"], intervention: "同次其余足踝、膝、大腿、腰骶和神经处理未逐项复查", note: "performed-without-itemized-retest", sourceRef: sourceRef("RAW-KNEE-001-D04", "L30-L47") }],
      },
    ],
  },
  {
    id: "RAW-KNEE-002",
    reviewStatus: "awaiting-owner-review",
    sourceDocuments: [rawDocument("RAW-KNEE-002-D01", "2024.11.3治疗记录.txt:40-48")],
    episodes: [{
      id: "RAW-KNEE-CF5A27E9589C",
      sessionDate: recorded("2024-11-03"),
      complaint: {
        branchId: "knee-terminal-flexion-discomfort",
        side: "left",
        rawSummary: "左膝内侧疼，屈膝末端疼，长时间屈膝后再走路会不舒服。",
        symptomQualities: ["疼痛", "不舒服"],
        currentActionIds: ["knee-flexion-end-range"],
        injuryActionIds: [],
        timing: { earliestOnset: notRecorded, latestOccurrence: recorded("2024-11-03 当次"), injuryEvent: notRecorded },
        sourceRef: sourceRef("RAW-KNEE-002-D01", "L41"),
      },
      findings: [
        { id: "RAW-KNEE-002-E01-F01", assessmentId: "knee-passive-flexion-end-range", side: "left", finding: "屈膝末端疼痛", sourceRef: sourceRef("RAW-KNEE-002-D01", "L41") },
        { id: "RAW-KNEE-002-E01-F02", assessmentId: "squat-movement-observation", side: "bilateral", finding: "下蹲向右侧偏", sourceRef: sourceRef("RAW-KNEE-002-D01", "L47") },
        { id: "RAW-KNEE-002-E01-F03", assessmentId: "popliteus-response", side: "right", finding: "记录为过紧", sourceRef: sourceRef("RAW-KNEE-002-D01", "L45") },
        { id: "RAW-KNEE-002-E01-F04", assessmentId: "psoas-response", side: "right", finding: "记录为过紧", sourceRef: sourceRef("RAW-KNEE-002-D01", "L44") },
        { id: "RAW-KNEE-002-E01-F05", assessmentId: "quadratus-lumborum-response", side: "right", finding: "记录为过紧", sourceRef: sourceRef("RAW-KNEE-002-D01", "L44") },
        { id: "RAW-KNEE-002-E01-F06", assessmentId: "pelvis-active-movement", side: "right", finding: "骨盆活动差", sourceRef: sourceRef("RAW-KNEE-002-D01", "L43") },
      ],
      treatmentExperiments: [{ id: "RAW-KNEE-002-E01-T01", findingIds: ["RAW-KNEE-002-E01-F01"], primaryTarget: "腓骨近端活动", targetType: "joint", intervention: "腓骨近端松动", attribution: "single-target", supportingInterventions: [], retestIds: ["RAW-KNEE-002-E01-R01"], sourceRef: sourceRef("RAW-KNEE-002-D01", "L41") }],
      retests: [{ id: "RAW-KNEE-002-E01-R01", treatmentExperimentId: "RAW-KNEE-002-E01-T01", actionId: "knee-flexion-end-range", before: "屈膝末端疼", after: "角度更大且不疼", result: "better", sourceRef: sourceRef("RAW-KNEE-002-D01", "L41") }],
      interventionsWithoutItemizedRetest: [],
    }],
  },
  {
    id: "RAW-KNEE-003",
    reviewStatus: "awaiting-owner-review",
    sourceDocuments: [rawDocument("RAW-KNEE-003-D01", "2024.11.5治疗记录.txt:36-47")],
    episodes: [{
      id: "RAW-KNEE-65EF52656C34",
      sessionDate: recorded("2024-11-05"),
      complaint: {
        branchId: "knee-step-down-posterior-discomfort",
        side: "right",
        rawSummary: "按记录中的下台阶方式完成时，在下降瞬间膝后不舒服。",
        symptomQualities: ["不舒服"],
        currentActionIds: ["step-down"],
        injuryActionIds: [],
        timing: { earliestOnset: notRecorded, latestOccurrence: recorded("2024-11-05 当次"), injuryEvent: notRecorded },
        sourceRef: sourceRef("RAW-KNEE-003-D01", "L45"),
      },
      findings: [{ id: "RAW-KNEE-003-E01-F01", assessmentId: "step-down-symptom-reproduction", side: "right", finding: "下降瞬间膝后不舒服", sourceRef: sourceRef("RAW-KNEE-003-D01", "L45") }],
      treatmentExperiments: [{ id: "RAW-KNEE-003-E01-T01", findingIds: ["RAW-KNEE-003-E01-F01"], primaryTarget: "腓骨近端活动", targetType: "joint", intervention: "腓骨近端松动", attribution: "single-target", supportingInterventions: [], retestIds: ["RAW-KNEE-003-E01-R01"], sourceRef: sourceRef("RAW-KNEE-003-D01", "L40,L45") }],
      retests: [{ id: "RAW-KNEE-003-E01-R01", treatmentExperimentId: "RAW-KNEE-003-E01-T01", actionId: "step-down", before: "下降瞬间膝后不舒服", after: "缓解", result: "better", sourceRef: sourceRef("RAW-KNEE-003-D01", "L45") }],
      interventionsWithoutItemizedRetest: [{ id: "RAW-KNEE-003-E01-I01", relatedFindingIds: ["RAW-KNEE-003-E01-F01"], intervention: "同次另有瘢痕、股内侧肌、超声及训练安排，未逐项复查膝后不适", note: "performed-without-itemized-retest", sourceRef: sourceRef("RAW-KNEE-003-D01", "L37-L46") }],
    }],
  },
  {
    id: "RAW-KNEE-004",
    reviewStatus: "awaiting-owner-review",
    sourceDocuments: [rawDocument("RAW-KNEE-004-D01", "2024.12.26治疗记录.txt:65-96")],
    episodes: [{
      id: "RAW-KNEE-F940D4117B4F",
      sessionDate: recorded("2024-12-26"),
      complaint: {
        branchId: "knee-patella-pressure-pain",
        side: "left",
        rawSummary: "左膝髌骨滑动异常，按压髌骨偏内侧疼，同时记录膝下痛。",
        symptomQualities: ["疼痛", "滑动异常"],
        currentActionIds: [],
        injuryActionIds: [],
        timing: { earliestOnset: notRecorded, latestOccurrence: recorded("2024-12-26 当次"), injuryEvent: notRecorded },
        sourceRef: sourceRef("RAW-KNEE-004-D01", "L72-L73"),
      },
      findings: [
        { id: "RAW-KNEE-004-E01-F01", assessmentId: "patella-glide-and-pressure", side: "left", finding: "髌骨滑动异常，按压偏内侧疼", sourceRef: sourceRef("RAW-KNEE-004-D01", "L72") },
        { id: "RAW-KNEE-004-E01-F02", assessmentId: "lateral-thigh-response", side: "left", finding: "髂胫束记录为过紧", sourceRef: sourceRef("RAW-KNEE-004-D01", "L74") },
        { id: "RAW-KNEE-004-E01-F03", assessmentId: "ankle-active-dorsiflexion", side: "right", finding: "背屈受限", sourceRef: sourceRef("RAW-KNEE-004-D01", "L70") },
        { id: "RAW-KNEE-004-E01-F04", assessmentId: "ankle-active-eversion", side: "right", finding: "外翻受限", sourceRef: sourceRef("RAW-KNEE-004-D01", "L70") },
        { id: "RAW-KNEE-004-E01-F05", assessmentId: "ankle-talus-fibula-mobility", side: "right", finding: "距骨和腓骨活动受限", sourceRef: sourceRef("RAW-KNEE-004-D01", "L71") },
      ],
      treatmentExperiments: [{ id: "RAW-KNEE-004-E01-T01", findingIds: ["RAW-KNEE-004-E01-F01"], primaryTarget: "左侧后侧组织拉伸方向（原文未细分）", targetType: "muscle-region", intervention: "左侧后侧拉伸", attribution: "single-target", supportingInterventions: [], retestIds: ["RAW-KNEE-004-E01-R01"], sourceRef: sourceRef("RAW-KNEE-004-D01", "L72,L92") }],
      retests: [{ id: "RAW-KNEE-004-E01-R01", treatmentExperimentId: "RAW-KNEE-004-E01-T01", actionId: "patella-press", before: "按压髌骨偏内侧疼", after: "疼痛缓解", result: "better", sourceRef: sourceRef("RAW-KNEE-004-D01", "L72") }],
      interventionsWithoutItemizedRetest: [{ id: "RAW-KNEE-004-E01-I01", relatedFindingIds: ["RAW-KNEE-004-E01-F01", "RAW-KNEE-004-E01-F02", "RAW-KNEE-004-E01-F03", "RAW-KNEE-004-E01-F04", "RAW-KNEE-004-E01-F05"], intervention: "同次其余肩颈、踝足、大腿、骨盆和超声处理未逐项复查这些发现", note: "performed-without-itemized-retest", sourceRef: sourceRef("RAW-KNEE-004-D01", "L79-L95") }],
    }],
  },
  {
    id: "RAW-KNEE-005",
    reviewStatus: "awaiting-owner-review",
    sourceDocuments: [rawDocument("RAW-KNEE-005-D01", "2024.7.12治疗记录.txt:73-84")],
    episodes: [{
      id: "RAW-KNEE-EA80FD3107C8",
      sessionDate: recorded("2024-07-12"),
      complaint: {
        branchId: "knee-terminal-flexion-discomfort",
        side: "right",
        rawSummary: "冲浪时右膝被别向外翻，之后伸膝受限、腘窝不适、被动屈膝末端疼。",
        symptomQualities: ["疼痛", "不适", "活动受限"],
        currentActionIds: ["knee-extension", "knee-flexion-end-range"],
        injuryActionIds: [],
        mechanism: "冲浪时膝外翻受伤",
        timing: { earliestOnset: notRecorded, latestOccurrence: recorded("2024-07-12 当次"), injuryEvent: notRecorded },
        sourceRef: sourceRef("RAW-KNEE-005-D01", "L74"),
      },
      findings: [
        { id: "RAW-KNEE-005-E01-F01", assessmentId: "knee-active-extension", side: "right", finding: "伸膝受限", sourceRef: sourceRef("RAW-KNEE-005-D01", "L74") },
        { id: "RAW-KNEE-005-E01-F02", assessmentId: "knee-passive-flexion-end-range", side: "right", finding: "被动屈膝末端疼痛", sourceRef: sourceRef("RAW-KNEE-005-D01", "L74") },
      ],
      treatmentExperiments: [{ id: "RAW-KNEE-005-E01-T01", findingIds: ["RAW-KNEE-005-E01-F02"], primaryTarget: "腓骨近端活动", targetType: "joint", intervention: "腓骨近端松动", attribution: "single-target", supportingInterventions: ["股外侧肌松解", "小腿三头肌松解", "腘肌松解", "伸膝促进"], retestIds: ["RAW-KNEE-005-E01-R01"], sourceRef: sourceRef("RAW-KNEE-005-D01", "L74-L77") }],
      retests: [{ id: "RAW-KNEE-005-E01-R01", treatmentExperimentId: "RAW-KNEE-005-E01-T01", actionId: "knee-flexion-end-range", before: "被动屈膝末端疼痛", after: "疼痛消失", result: "better", sourceRef: sourceRef("RAW-KNEE-005-D01", "L74") }],
      interventionsWithoutItemizedRetest: [],
    }],
  },
  {
    id: "RAW-KNEE-006",
    reviewStatus: "awaiting-owner-review",
    sourceDocuments: [rawDocument("RAW-KNEE-006-D01", "2024.7.17治疗记录.txt:26-34")],
    episodes: [{
      id: "RAW-KNEE-9AFFA1E18137",
      sessionDate: recorded("2024-07-17"),
      complaint: {
        branchId: "knee-extension-medial-discomfort",
        side: "right",
        rawSummary: "站直右腿时膝内侧疼；同期臀部酸痛的原文猜测未作为评估事实。",
        symptomQualities: ["疼痛"],
        currentActionIds: ["standing-knee-extension"],
        injuryActionIds: [],
        timing: { earliestOnset: notRecorded, latestOccurrence: recorded("2024-07-17 当次"), injuryEvent: notRecorded },
        sourceRef: sourceRef("RAW-KNEE-006-D01", "L27"),
      },
      findings: [{ id: "RAW-KNEE-006-E01-F01", assessmentId: "standing-knee-extension-symptom", side: "right", finding: "站直腿时膝内侧疼", sourceRef: sourceRef("RAW-KNEE-006-D01", "L27") }],
      treatmentExperiments: [
        { id: "RAW-KNEE-006-E01-T01", findingIds: ["RAW-KNEE-006-E01-F01"], primaryTarget: "股外侧肌方向", targetType: "muscle", intervention: "股外侧肌松解", attribution: "single-target", supportingInterventions: [], retestIds: ["RAW-KNEE-006-E01-R01"], sourceRef: sourceRef("RAW-KNEE-006-D01", "L28") },
        { id: "RAW-KNEE-006-E01-T02", findingIds: ["RAW-KNEE-006-E01-F01"], primaryTarget: "内收肌主动控制", targetType: "movement-control", intervention: "内收肌发力", attribution: "single-target", supportingInterventions: [], retestIds: ["RAW-KNEE-006-E01-R02"], sourceRef: sourceRef("RAW-KNEE-006-D01", "L28") },
      ],
      retests: [
        { id: "RAW-KNEE-006-E01-R01", treatmentExperimentId: "RAW-KNEE-006-E01-T01", actionId: "standing-knee-extension", before: "膝内侧疼", after: "缓解一点点", result: "partial", sourceRef: sourceRef("RAW-KNEE-006-D01", "L28") },
        { id: "RAW-KNEE-006-E01-R02", treatmentExperimentId: "RAW-KNEE-006-E01-T02", actionId: "standing-knee-extension", before: "仍有膝内侧疼", after: "缓解较多", result: "better", sourceRef: sourceRef("RAW-KNEE-006-D01", "L28") },
      ],
      interventionsWithoutItemizedRetest: [{ id: "RAW-KNEE-006-E01-I01", relatedFindingIds: ["RAW-KNEE-006-E01-F01"], intervention: "同次其余腰髋、大腿区域处理和臀桥未逐项复查膝内侧疼", note: "performed-without-itemized-retest", sourceRef: sourceRef("RAW-KNEE-006-D01", "L29-L33") }],
    }],
  },
  {
    id: "RAW-KNEE-007",
    reviewStatus: "awaiting-owner-review",
    sourceDocuments: [rawDocument("RAW-KNEE-007-D01", "2024.8.8治疗记录.txt:3-20")],
    episodes: [{
      id: "RAW-KNEE-C511259843A8",
      sessionDate: recorded("2024-08-08"),
      complaint: {
        branchId: "knee-support-contact-pain",
        side: "right",
        rawSummary: "鸟狗伸腿时右膝作为支撑侧会疼。",
        symptomQualities: ["疼痛"],
        currentActionIds: ["bird-dog-leg-extension"],
        injuryActionIds: [],
        timing: { earliestOnset: notRecorded, latestOccurrence: recorded("2024-08-08 当次"), injuryEvent: notRecorded },
        sourceRef: sourceRef("RAW-KNEE-007-D01", "L18"),
      },
      findings: [{ id: "RAW-KNEE-007-E01-F01", assessmentId: "bird-dog-support-symptom", side: "right", finding: "支撑时膝痛", sourceRef: sourceRef("RAW-KNEE-007-D01", "L18") }],
      treatmentExperiments: [
        { id: "RAW-KNEE-007-E01-T01", findingIds: ["RAW-KNEE-007-E01-F01"], primaryTarget: "支撑面压力调整", targetType: "symptom-management", intervention: "在膝下增加软垫", attribution: "single-target", supportingInterventions: [], retestIds: ["RAW-KNEE-007-E01-R01"], sourceRef: sourceRef("RAW-KNEE-007-D01", "L18") },
        { id: "RAW-KNEE-007-E01-T02", findingIds: ["RAW-KNEE-007-E01-F01"], primaryTarget: "腓骨远端活动", targetType: "joint", intervention: "腓骨远端松动", attribution: "single-target", supportingInterventions: [], retestIds: ["RAW-KNEE-007-E01-R02"], sourceRef: sourceRef("RAW-KNEE-007-D01", "L18-L19") },
      ],
      retests: [
        { id: "RAW-KNEE-007-E01-R01", treatmentExperimentId: "RAW-KNEE-007-E01-T01", actionId: "bird-dog-leg-extension", before: "支撑时膝痛", after: "垫软后无缓解", result: "same", sourceRef: sourceRef("RAW-KNEE-007-D01", "L18") },
        { id: "RAW-KNEE-007-E01-R02", treatmentExperimentId: "RAW-KNEE-007-E01-T02", actionId: "bird-dog-leg-extension", before: "支撑时膝痛仍在", after: "缓解", result: "better", sourceRef: sourceRef("RAW-KNEE-007-D01", "L18-L19") },
      ],
      interventionsWithoutItemizedRetest: [],
    }],
  },
  {
    id: "RAW-KNEE-008",
    reviewStatus: "awaiting-owner-review",
    sourceDocuments: [rawDocument("RAW-KNEE-008-D01", "2024.8.8治疗记录.txt:21-32")],
    episodes: [{
      id: "RAW-KNEE-7304FC069D97",
      sessionDate: recorded("2024-08-08"),
      complaint: {
        branchId: "knee-squat-pain-or-scraping",
        side: "right",
        rawSummary: "下蹲时右膝同时有刮擦感和弹响。",
        symptomQualities: ["刮擦感", "弹响"],
        currentActionIds: ["squat"],
        injuryActionIds: [],
        timing: { earliestOnset: notRecorded, latestOccurrence: recorded("2024-08-08 当次"), injuryEvent: notRecorded },
        sourceRef: sourceRef("RAW-KNEE-008-D01", "L25"),
      },
      findings: [
        { id: "RAW-KNEE-008-E01-F01", assessmentId: "squat-symptom-reproduction", side: "right", finding: "下蹲时有刮擦感", sourceRef: sourceRef("RAW-KNEE-008-D01", "L25") },
        { id: "RAW-KNEE-008-E01-F02", assessmentId: "squat-symptom-reproduction", side: "right", finding: "下蹲时有弹响", sourceRef: sourceRef("RAW-KNEE-008-D01", "L25") },
      ],
      treatmentExperiments: [
        { id: "RAW-KNEE-008-E01-T01", findingIds: ["RAW-KNEE-008-E01-F01", "RAW-KNEE-008-E01-F02"], primaryTarget: "腓骨近端与远端活动组合", targetType: "joint", intervention: "连续完成腓骨近端和远端松动", attribution: "combined-targets", supportingInterventions: [], retestIds: ["RAW-KNEE-008-E01-R01"], sourceRef: sourceRef("RAW-KNEE-008-D01", "L26-L29") },
        { id: "RAW-KNEE-008-E01-T02", findingIds: ["RAW-KNEE-008-E01-F02"], primaryTarget: "下蹲时髋膝轨迹控制", targetType: "movement-control", intervention: "从膝外侧提供手动支持后再次下蹲", attribution: "single-target", supportingInterventions: [], retestIds: ["RAW-KNEE-008-E01-R02"], sourceRef: sourceRef("RAW-KNEE-008-D01", "L29") },
      ],
      retests: [
        { id: "RAW-KNEE-008-E01-R01", treatmentExperimentId: "RAW-KNEE-008-E01-T01", actionId: "squat", before: "刮擦感并有弹响", after: "刮擦感消失，弹响仍在", result: "partial", sourceRef: sourceRef("RAW-KNEE-008-D01", "L29") },
        { id: "RAW-KNEE-008-E01-R02", treatmentExperimentId: "RAW-KNEE-008-E01-T02", actionId: "squat", before: "仍有弹响", after: "弹响改善", result: "better", sourceRef: sourceRef("RAW-KNEE-008-D01", "L29") },
      ],
      interventionsWithoutItemizedRetest: [
        { id: "RAW-KNEE-008-E01-I01", relatedFindingIds: ["RAW-KNEE-008-E01-F01", "RAW-KNEE-008-E01-F02"], intervention: "复现前已完成大腿外侧、髂胫束、腰大肌和股外侧肌处理，原文未逐项复查", note: "performed-without-itemized-retest", sourceRef: sourceRef("RAW-KNEE-008-D01", "L22-L25") },
        { id: "RAW-KNEE-008-E01-I02", relatedFindingIds: ["RAW-KNEE-008-E01-F02"], intervention: "随后安排屈髋侧移与单髋支撑，原文未记录训练后复查", note: "performed-without-itemized-retest", sourceRef: sourceRef("RAW-KNEE-008-D01", "L30-L31") },
      ],
    }],
  },
];

export const KNEE_KNOWLEDGE_REVIEW_PACKAGE: KnowledgeReviewPackage = {
  id: "rehabmind-raw-knee-review-sample-2026-08-29",
  contractVersion: 1,
  bodyRegion: "knee",
  status: "review-candidate",
  extraction: {
    inputCollectionId: "COL-AI-RAW",
    method: "raw-segment-review",
    sourceFileCount: 267,
    sourceSegmentCount: 1112,
    kneeCandidateCount: 563,
    includedCandidateIds: [
      "RAW-KNEE-22F355F1B571",
      "RAW-KNEE-2E9D4EC80CA5",
      "RAW-KNEE-FAAEDDD75256",
      "RAW-KNEE-C06633F10CA4",
      "RAW-KNEE-CF5A27E9589C",
      "RAW-KNEE-65EF52656C34",
      "RAW-KNEE-F940D4117B4F",
      "RAW-KNEE-EA80FD3107C8",
      "RAW-KNEE-9AFFA1E18137",
      "RAW-KNEE-C511259843A8",
      "RAW-KNEE-7304FC069D97",
    ],
  },
  actionDefinitions,
  assessmentDefinitions,
  complaintBranches,
  sourceCases,
};
